### ISSUE TITLE
Multi-finger gestures (two-finger swipe, spread an pinch) confused in PocketBook Era

### ISSUE THREAD

**Issue by mafes1** [koreader/koreader#10950]
* KOReader version: KOReader 2023.08 "Lavender"
* Device: PocketBook Era (PB700)

#### Issue

Multi-finger gestures do not work properly. Two-finger swipe and spread and pinch are not correctly recognised. These gestures are "confused". Performing any of these gestures (and the default settings for gestures), font size may be increased or decreased, illumination may be altered, bookmarks or table of contents may appear, etc. indistinctly. I tried disabling two-finger (vertical) swipe gestures but spread and pinch continue to not being distinguished among them.

Please, note that spread and pinch are working properly in the built-in reader of PocketBook.

It happens in a new PocketBook Era with the last firmware U700.6.8.1957.

The same problem also exists with KOReader version 2023.06.

#### Steps to reproduce
1. Open an epub file with KOReader.
2. Perform multi-finger gestures (two-finger swipe, spread and pinch). Most of them may not be correctly recognised.
##### `crash.log` (if applicable)
`crash.log` file with  *verbose* debug logging enabled. I tried many times spreading (increase font-size by default). It was not correctly recognised most times. Note that I first opened an .epub file.

[crash.log](https://github.com/koreader/koreader/files/12716436/crash.log)

**Comment by pazos** [comment]
I'm not sure if we actually support MT on Pocketbooks at all.

**Comment by NiLuJe** [comment]
Ouch, looking at the logs, given the amount of `NO TOUCH INFO` spam, I'm guessing something's rotten in the state of Denmark?

**Comment by NiLuJe** [comment]
Skimming the logs, the only thing ever being generated for slots > 0 are contact lifts, so I imagine that this branch in particular is a bit too restrictive:

https://github.com/koreader/koreader-base/blob/75cbf4647ab0cd020c3050656dc0d21cc6c21047/ffi/input_pocketbook.lua#L61-L70

Dumping what the parameters you actually get would be helpful. I would imagine it's something like the amount of contact points, and making the branch & loop dynamic instead of only whitelisting 2 would be more helpful; but that obviously depends on how the hell that thing actually looks like in practice ;).

**Comment by mafes1** [comment]
> Skimming the logs, the only thing ever being generated for slots > 0 are contact lifts, so I imagine that this branch in particular is a bit too restrictive:
> 
> https://github.com/koreader/koreader-base/blob/75cbf4647ab0cd020c3050656dc0d21cc6c21047/ffi/input_pocketbook.lua#L61-L70
> 
> Dumping the parameters you actually get would be helpful. I would imagine it's something like the amount of contact points, and making the branch & loop dynamic instead of only whitelisting 2 would be more helpful; but that obviously depends on how the hell that thing actually looks like in practice ;).

Thank you very much. I added some lines in the debugger to see the values of the parameters.

I used koreader repo and tag v2023.08-41-ged885a79b, recompiling for pocketbook, for testing.

The crash.log is always trying to increase fontsize with a spread gesture (default settings), after opening an epub file.

[crash.log](https://github.com/koreader/koreader/files/12732031/crash.log)

This is what I modified (I only added logger lines):

```
local function translateEvent(t, par1, par2)
    if eventq == nil then
        return 0
    end
    updateTimestamp()
    logger.dbg("Value of t: ", t)
    if t == C.EVT_INIT then
        inkview.SetPanelType(C.PANEL_DISABLED);
    elseif t == C.EVT_POINTERDOWN then
        num_touch = 1
        genEmuEvent(C.EV_ABS, C.ABS_MT_TRACKING_ID, 0)
        genEmuEvent(C.EV_ABS, C.ABS_MT_POSITION_X, par1)
        genEmuEvent(C.EV_ABS, C.ABS_MT_POSITION_Y, par2)
    elseif t == C.EVT_MTSYNC then
        logger.dbg("-Value of num_touch: ", num_touch)
        logger.dbg("-Value of par2: ", par2)
        if num_touch > 0 and par2 == 2 then
            num_touch = 2
            for i = 0, 1 do
 	        logger.dbg("---Value of i: ", i)
 	        logger.dbg("---Value of C.EV_ABS: ", C.EV_ABS)
 	        logger.dbg("---Value of C.ABS_MT_SLOT: ", C.ABS_MT_SLOT)
 	        logger.dbg("---Value of C.ABS_MT_TRACKING_ID: ", C.ABS_MT_TRACKING_ID)
 	        logger.dbg("---Value of C.ABS_MT_POSITION_X: ", C.ABS_MT_POSITION_X)
 	        logger.dbg("---Value of C.ABS_MT_POSITION_Y: ", C.ABS_MT_POSITION_Y)
 	        logger.dbg("---Value of C.EV_SYN: ", C.EV_SYN)
 	        logger.dbg("---Value of C.SYN_REPORT: ", C.SYN_REPORT)
	        genEmuEvent(C.EV_ABS, C.ABS_MT_SLOT, i);
                genEmuEvent(C.EV_ABS, C.ABS_MT_TRACKING_ID, i);
                local mt = compat2.GetTouchInfoI(i)
	        logger.dbg("---Value of mt: ", mt)
 	        logger.dbg("---Value of mt.x: ", mt.x)
	        logger.dbg("---Value of mt.y: ", mt.y)
                genEmuEvent(C.EV_ABS, C.ABS_MT_POSITION_X, mt.x)
                genEmuEvent(C.EV_ABS, C.ABS_MT_POSITION_Y, mt.y)
                genEmuEvent(C.EV_SYN, C.SYN_REPORT, 0)
            end
        elseif par2 == 0 then
            for i = 0, 1 do
 	        logger.dbg("---Value of i: ", i)
 	        logger.dbg("---Value of C.EV_ABS: ", C.EV_ABS)
 	        logger.dbg("---Value of C.EV_SYN: ", C.EV_SYN)
 	        logger.dbg("---Value of C.ABS_MT_SLOT: ", C.ABS_MT_SLOT)
 	        logger.dbg("---Value of C.ABS_MT_TRACKING_ID: ", C.ABS_MT_TRACKING_ID)
 	        logger.dbg("---Value of C.SYN_REPORT: ", C.SYN_REPORT)
                genEmuEvent(C.EV_ABS, C.ABS_MT_SLOT, i);
                genEmuEvent(C.EV_ABS, C.ABS_MT_TRACKING_ID, -1);
                genEmuEvent(C.EV_SYN, C.SYN_REPORT, 0)
            end
        else
 	    logger.dbg("---Value of C.SYN_REPORT: ", C.SYN_REPORT)
 	    logger.dbg("---Value of C.EV_SYN: ", C.EV_SYN)
            genEmuEvent(C.EV_SYN, C.SYN_REPORT, 0)
        end
```

**Comment by NiLuJe** [comment]
(FWWI, the C. are constants, so that's just noise).

That looks considerably saner, and the code seems to behave just fine (e.g., I'm seeing a fair number of `spread` gestures being detected.

**Comment by mafes1** [comment]
In the crash.log, there are only "real" spread gestures. Thus, every pinch and two finger swipe gestures are incorrect because I was doing only spread gestures. In the crash.log, I count 10 spread gestures (correctly recognised), 15 pinch gestures (which should be spread gestures) and 24 two finger swipes (which should also be spread gestures).

This issue is not happening on the built-in reader of PB700, so the device should not be faulty.

I can record a short video showing this issue if you need it.

**Comment by NiLuJe** [comment]
That's not something I can really remote debug, hence the `help-wanted` tag ;).

**Comment by NiLuJe** [comment]
A good start would probably be' to handle those `GetTouchInfoI` failures, ideally sanely (because without a better API, the best I can see is dropping the event if x & y == 0, unless the `active` field is somewhat usable there, too...).

**Comment by NiLuJe** [comment]
i.e., https://github.com/NiLuJe/koreader-base/compare/koreader:koreader-base:master...pb-input-mt 

But, given your logs, the contacts reported by `GetTouchInfoI` always looks *very* close to each other, so I fear it may simply be a case of that thing just doesn't work how we expect it to.

If someone can dig up an actual documentation of how PB's `EVT_MTSYNC` event is supposed to work, that might help...

**Comment by mafes1** [comment]
> i.e., [NiLuJe/koreader-base@koreader:koreader-base:master...pb-input-mt](https://github.com/NiLuJe/koreader-base/compare/koreader:koreader-base:master...pb-input-mt)
> 
> But, given your logs, the contacts reported by `GetTouchInfoI` always look _very_ close to each other, so I fear it may simply be a case of that thing just doesn't work how we expect it to.
> 
> If someone can dig up an actual documentation of how PB's `EVT_MTSYNC` event is supposed to work, that might help...

Thank you. With these changes, no gesture is working. I can not even tap in the screen and navigate (only physical buttons). I attach a crash.log with debug enabled.

https://github.com/koreader/koreader-base/blob/a13c7417527d685c2b9e89c0afc4aa7ddddb0a49/ffi/input_pocketbook.lua

[crash.log](https://github.com/koreader/koreader/files/12765850/crash.log)

**Comment by NiLuJe** [comment]
Someone with actual access to a device will have to figure that one out ;).

**Comment by NiLuJe** [comment]
I've updated the branch with more logging, and possibly a fix for the missing end of frames in the first iteration, so you can give that a try...

(Assuming I didn't break everything because of the funky require for the logging...).

**Comment by mafes1** [comment]
Sorry, but I cannot find where there are these new changes... I do not find new commited changes for 30th september in the link provided above

**Comment by NiLuJe** [comment]
Still the tip of the same branch: https://github.com/koreader/koreader-base/compare/master...NiLuJe:koreader-base:pb-input-mt

i.e., currently, https://github.com/NiLuJe/koreader-base/blob/d2d574208b16ef0a7924b3a6085901d5025fb96e/ffi/input_pocketbook.lua

**Comment by mafes1** [comment]
Thank you very much for your effort. Unfortunetly, it is still not working. I am experiencing a "strange" behaviour. Some gestures sometimes are not recognised (nothing happens), which means that single and/or long taps sometimes fails (i.e. select options from the menu, select text, etc.). Swipes sometimes are not recognised (one finger), and spread and pinch are normally not recognised. I even experienced a couple of crashes when doing spread and pinch.
I attach a crash.log
[crash.log](https://github.com/koreader/koreader/files/12797471/crash.log)

**Comment by NiLuJe** [comment]
Ohkay, yeah, getTouchInfoI definitely behaves in a way that nobody expected.

I assume there's up to 10 coordinates per slot being buffered, and for some reason it doesn't return the last one or... something.

Anyway, pushed a commit that restores the (current) behavior of avoiding that for slot 0, but that doesn't really solve our MT issues ;o).

**Comment by NiLuJe** [comment]
> Which is where it appears even more broken (i.e., it looks like querying slot 1 sometimes reports stale coordinates form slot 0 o_O).

To test that theory, try something like moving two fingers in opposite corners of the screen, I'm pretty sure that should make it obvious that InkView is reporting completely broken stuff...

**Comment by mafes1** [comment]
Thank you! Now single taps are working as expected. Multi-touch swipes, spread and pinch are rarely recognised.

I tried different gestures in this crash.log. Many gestures were moving two fingers in opposite corners of the screen (almost all at the end of the file).

[crash.log](https://github.com/koreader/koreader/files/12807134/crash.log)

**Comment by NiLuJe** [comment]
Yeaaah, I really can't make heads nor tail of what `GetTouchInfoI` returns, so, given that InkView is kind of a black box on that front, someone with a device will have to figure it out (or poke PocketBook for more details).

**Comment by NiLuJe** [comment]
> (or poke PocketBook for more details)

IIRC, @rjd22 had mild success with that in the past ;).

**Comment by rjd22** [comment]
*poof!*  - You summoned me? :P

I will have to check this on my own device before contacting Pocketbook with it. That way I understand what's going on better myself.

Sadly because of personal reasons I don't have a lot of time right now so patience is needed ^^°.

**Comment by NiLuJe** [comment]
Thanks ;).

In the meantime, I'll PR the branch in question (mostly because that bit of code had been irking me for a while, regardless ;p).

**Comment by NiLuJe** [comment]
Keep in mind, AFAICT, on older FW versions, we [`emulate GetTouchInfoI`](https://github.com/koreader/koreader-base/blob/f56d882d4baf784fe061c9eedd3f74540bfcd490/input/inkview-compat.c#L65-L68).

That's not the case for the OP, we're using the native version there.

Also, in the v6 SDKs, I can see new, even weirder and badly documented Touch stuff, which seems to corroborate my "stuff seems buffered for a while" theory: https://github.com/pocketbook/SDK_6.3.0/blob/dd8de463733a2bc0d53d1214b64734586fac427e/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/local/include/inkview.h#L2989-L3010
