### ISSUE TITLE
[Pocketbook Era] Accelerometer auto-orientation inverted after sleep

### ISSUE THREAD

**Issue by luisbc92** [koreader/koreader#11033]
* KOReader version: 2023.08
* Device: Pocketbook Era

#### Issue

When waking up from sleep, KOReader will occasionally and actively flip the orientation upside down from the position detected by the accelerometer.

This problem will persist until exiting to the home menu and coming back to KOReader.

#### Steps to reproduce

- Load a document in KOReader.
- Put Pocketbook in sleep mode.
- Wake it back up.
- Screen will be upside down, even after physically moving the device around.
- Profit?

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by grabi678** [comment]
Also happens on Pocketbook Inkpad Color.

**Comment by Biep** [comment]
Same here.  I am quite willing to test experimental code on my Era.

**Comment by jospalau** [comment]
I got recently a PocketBook Era and I have been experiencing this as well. I have disabled the accelerometer adding the following into /etc/init.d/rcS:
chmod 000 /sys/gsensor/*

I still have to test how consistent is but in principle it seems to be working.

I find this device to be the snappiest of all.

**Comment by Biep** [comment]
I simply told KOReader to ignore accelerometer rotation events (Cog wheel - Screen - Rotation).

Something different: some elements are missing in the menu.  Searching metadata is one.  The WiFi status in the Status bar is another.  Just reporting it for in case it points to something of importance.

**Comment by jospalau** [comment]
The problem you reported happens to me even configuring KOReader to ignore accelerometer. I think is the stock program setting the screensaver the culprit.

I use searching metadata from a quick menu action and I don't use the WiFi status in the status bar.

**Comment by Biep** [comment]
For me, ignoring the rotation events solves the problem.

**Comment by NiLuJe** [comment]
> Searching metadata is one. 

What are you thinking of, exactly? Unless you've disabled the calibre plugin, that one doesn't make sense.

>The WiFi status in the Status bar is another.

That one probably does, on the other hand. PB is a second-class citizen, I warned you ;).

**Comment by Biep** [comment]
Yes, you warned me.  I realise I took a risk - but the openness of PB, and the 64G (actually 58G) storage seem well worth it.

The magnifying glass menu doesn't show the "Search metadata" line.  Plugin management tells me that all plugins are on, except Perception Expander, Progress Sync, Vocabulary Builder and Wallabag.

**Comment by NiLuJe** [comment]
There's no "Search metadata" entry, only calibre's.

![calibre_meta](https://github.com/koreader/koreader/assets/111974/c43fc6b8-3053-4d2b-84ae-421abfde9650)

**Comment by Biep** [comment]
![2024-01-23-114714](https://github.com/koreader/koreader/assets/12461597/a115fe18-00d3-4c43-9fe0-3a35a96bcfa4)

**Comment by NiLuJe** [comment]
Which implies the calibre pugin is disabled ;).

**Comment by Biep** [comment]
![2024-01-23-133504](https://github.com/koreader/koreader/assets/12461597/94e2dccc-1c7a-48d6-9831-f08230c43f99)
![2024-01-23-133539](https://github.com/koreader/koreader/assets/12461597/14454595-c60f-4a0c-be9a-13e5d81ab531)
![2024-01-23-133618](https://github.com/koreader/koreader/assets/12461597/1bfb41d5-7178-4568-9f9f-abfeb5dfd4bf)
![2024-01-23-133640](https://github.com/koreader/koreader/assets/12461597/9e80735e-9c0f-4722-9390-157e6250a5e2)

**Comment by NiLuJe** [comment]
Check your logs for startup failures, and settings for custom menu sorting?

**Comment by Biep** [comment]
(I had re-enabled the four I had disabled before.  And the above were taken right after starting the e-reader and then KOReader.  And KOReader is almost a fresh install - I did a bit to set viewing preferences.)
[crash.log](https://github.com/koreader/koreader/files/14024243/crash.log)

**Comment by NiLuJe** [comment]
Not that it should matter, but try w/ "Start with" at its default, file manager, instead of last document.

**Comment by Frenzie** [comment]
Does the calibre plugin show that menu entry if it doesn't have any
metadata in the first place?

**Comment by NiLuJe** [comment]
Yeah, the top-level entry is always there. (Same for OPDS).

**Comment by Biep** [comment]
Simply writing some more books from Calibre, and refreshing the metadata, did not make the entry appear.
In trying something more rigorous I found a small bug:  If the home folder does not exist, one cannot set it either, as going there requires starting in a nonexistent folder.

**Comment by Biep** [comment]
Yes!  I am not quite sure *what* did the trick, but a complete reset, with a new location for the documents, made the entry appear.  Clicking it and starting a search allowed searching for a library, and after that all seems hunkey-dorey.

**Comment by Biep** [comment]
But I think @Frenzie may be right - I have never yet seen the OPDS entry.  Just checked on the Kobo Aura One, but it isn't visible there either.

**Comment by pazos** [comment]
Nothing did the trick. Search metadata, by default, is only available on the FM, unless you changed the plugin settings

**Comment by Biep** [comment]
FM?

**Comment by NiLuJe** [comment]
File Manager. And, yeah, good idea, see if the menu search in [hamburger] > Help can pull it out from somewhere ;).

**Comment by NiLuJe** [comment]
Did you migrate settings or sidecars from your previous device, or did you start from scratch?

**Comment by NiLuJe** [comment]
What both the calibre & OPDS entries have in common is that they're gated behind a `if not self.ui.view then` check in their plugin's `addToMainMenu`...

I've never seen that be a problem anywhere, ever, but, it is a strange coincidence ;).

**Comment by NiLuJe** [comment]
> sidecars

Those would be the `.sdr` folders for each document files ;). (**S**i**D**eca**R**)

**Comment by Biep** [comment]
Aha.
By the way, @pazos, before the Calibre Metadata Search didn't show up when bringing up the menu from the file manager either - so **something** changed.

**Comment by pazos** [comment]
> Aha. By the way, @pazos, before the Calibre Metadata Search didn't show up when bringing up the menu from the file manager either - so **something** changed.

I don't think so. All your screenshots in this ticket are made in the reader, so there's no confirmation of that "issue"

I would gladly be proven wrong, so repro steps are welcome.

**Comment by Biep** [comment]
Repro would be hard, as it works now.  I suppose technically I could go through it all again..

But you **may** be right - though I thought that my search for the entry (which I thought might have moved) I had been pretty exhaustive.
And BTW, *OPDS catalog* has shown up too now - some time **after** the *Calibre metadata search* showed up.  I have been playing a bit more with the Era, but I really couldn't say what I have done to create that change.

**Comment by jospalau** [comment]
Being a second class citizen I think KOReader works pretty well in this device.

**Comment by Biep** [comment]
Yes, it does.  Still a happy camper here.
One little thing: because of the auto-orientation issue I read books with inverted orientation.  This does not propagate completely:
- The file manager does not turn around, nor does my gesture for inverting the orientation work there.
- The forward and backward buttons don't interchange, so the arrows on them point the wrong way.

**Comment by Biep** [comment]
Another thing - with I seem to remember I have had with the Aura One too, in the past - is with the screen light.  I have it at 1%.  When I switch it of (with a gesture) and go to another document or the file manager, it goes back on.  I seem unable to switch it off completely - it seems to hold only for the current document (or file manager).

Also - and this I *certainly* have at times with the Kobo Aura One too - the warmth setting doesn't translate faithfully in true hue.  The light may still be quite cold even if the setting is at 100% warmth.

**Comment by mmunce** [comment]
Coming back to the original issue I also noticed the Orientation of my Era to flipped after sleep.

I currently have applied the patch mentioned in #10123 for fixing the Buttons.
but the Orientation is always flipped.

**Comment by theboomr** [comment]
Not sure if there's anyone able to work on this, but I am still experiencing this rotation issue on my Era Color. It happens even if I have set koreader to ignore accelerometer events, which means about half the time when I open a book, I have to manually go flip the orientation, which is not a huge issue but over time it's definitely been quite a nuisance. I think what someone else mentioned might be correct, that it has to do with the OS screensaver for sleep mode, which always presents in portrait orientation with buttons on the right side. Since I am left handed, I often am using the reader the other way around, so that may account for why this occurs so regularly.

I just realized that if I turn off the auto rotation in the OS settings, the issue seems to be gone; koreader never flips to the wrong orientation (but also can't do accelerometer detection, since it's evidently fully disabled in the OS). But then this is an issue when I want to use the device left handed, since the OS has no way to do that if auto rotation is disabled.

**Comment by MJVgeek** [comment]
It also happens in my PocketBook Verse Pro Color. My workaround is using a profile that auto-executes on waking up and starting KOReader that sets the rotation to 0º.

**Comment by theboomr** [comment]
> It also happens in my PocketBook Verse Pro Color. My **workaround** was creating a profile that automatically executes upon waking and initiating KOReader. This profile sets the rotation to 0 degrees. 

Could you share how to get that set up? Sounds like it might be the best option so far

**Comment by MJVgeek** [comment]
> Could you share how to get that set up? Sounds like it might be the best option so far

1. Go to Top Menu > Tools > Profiles > New (and give it a name) > Select that Profile > Edit Actions > Device > Rotation > select 0º

1. Go back (end of menu arrow) to the first Tool Menu (where the Edit actions is) > Auto-execute > tick on KOReader start and on wake-up.

That's it — you have created the auto-execute profile.

**Comment by Biep** [comment]
Just created the profile, and some quick checks seem to indicate that the inversion issue is solved this way.
There still is a minor residual issue, though, which seems an unrelated bug:
- When I close the cover when in ***landscape*** mode, and later reopen it in ***portrait*** mode, the profile visibly executes (the notification for the orientation reset to 0˚ is shown) , and all is well.
- When I close the cover when in ***portait*** mode, and later reopen it in ***landscape*** mode, the profile does not visibly execute, and the document remains in portrait mode.  Tilting to portrait mode and back solves that.

**Comment by Biep** [comment]
Upon further use, I find that the profile is not always executed - not when in the file manager, for instance.
And sometimes it thinks it is at 0°, even though the screen is inverted.  Rotating 180° puts it straight up, but executing the profile then turns it upside-down again.
So while helpful, there is still quite a bit to go beyond this workaround.
But many thanks for suggesting it!

**Comment by Biep** [comment]
The issue seems back full force.  The device **thinks** it is upside-down, so a 0° orientation will make it show the file upside-down, and an 90° inversion is needed to show it upright.  And then, soonish, it realises its error, and turns the document again.  And in all this the forward and backward buttons trade places too.
When exiting to the native software the screen sometimes shows upside-down, but then quickly corrects itself.  So the issue is present there too, it seems, but they have found a way to recognise and correct it.  If KOReader could somehow tap into that correction, all would be well.

I now have my profile tell me when it runs, and I see it makes no difference to the orientation of the screen in portrait mode.

**Comment by theboomr** [comment]
Yeah I forgot to leave another comment but setting up the profile did not fix the issue at all for me either on my Era Color.

I don't think the native software/home screen is "recognizing" the problem exactly; rather, I think, when the device is asleep, the sleep screen always orients in one direction only, and when you wake it up inverted from that, KOReader gets confused about what direction is which because the accelerometer is reporting one thing, but the sleep screen made the device be in the inverted orientation, which the Pocketbook OS is aware of but KOReader is not.

I think I explained that badly, but...sigh. Unfortunately I have entirely given up on using auto rotation at all, it's way too frustrating.

**Comment by rauwman** [comment]
Yes i tested a lot. But atm using my method mentioned above was the simplest for now. When I start reading i don’t change the position. I only have to chose it before waking it up from sleep.
Hopefully it can be fixed to work like the default reading app.

**Comment by Biep** [comment]
I have a gesture to invert the rotation - a counterintuitive one, as it is meant to be performed while the screen (and the gesture interpreter) is inverted.

I believe there must be  command to activate the rotation sensor, and that the official PB software is giving that after waking up and the like.  KOReader, unaware of that gesture, instead reads and believes the outdated rotation setting.

**Comment by pkecerski** [comment]
As a recent Pocketbook Era owner I can confirm that this is still an issue in 2025.08.
It only goes away when I turn off the G-sensor system wise (i.e. in Pocketbook setting not in KOReader).

Wouldn't it be possible to add a line of code that executes on wake from sleep that checks the device ID for Pocketbook Era models and whether the G-sensor is turned on system-wise and only if both are true tells KOReader to invert it's orientation?

**Comment by jannickfahlbusch** [comment]
Hi all, 

I just submitted https://github.com/koreader/koreader/pull/14895 which attempts to fix the issue (Which in turn needs https://github.com/koreader/koreader-base/pull/2260 in order to have the function available through Lua).

It also enables the PB700 to auto-turn the current page into the current orientation which it also did not for me before.
The fix is working well enough for my daily reading - the initial rotation after the wakeup is visible and takes around half a second to take effect which is completel fine for me.

Could someone else test the change as well and report back? :)

**Comment by theboomr** [comment]
> Hi all, 
> 
> I just submitted https://github.com/koreader/koreader/pull/14895 which attempts to fix the issue (Which in turn needs https://github.com/koreader/koreader-base/pull/2260 in order to have the function available through Lua).
> 
> It also enables the PB700 to auto-turn the current page into the current orientation which it also did not for me before.
> The fix is working well enough for my daily reading - the initial rotation after the wakeup is visible and takes around half a second to take effect which is completel fine for me.
> 
> Could someone else test the change as well and report back? :)

This is awesome news! I had given up hope that it would ever get addressed. Should I be able to test the changes in the nightly build?

**Comment by Frenzie** [comment]
Yes, it'll be in today's nightly.

**Comment by Biep** [comment]
# 🙌🥳

**Comment by jannickfahlbusch** [comment]
The change didn't work in all cases, especially when the rotation is locked. https://github.com/koreader/koreader/pull/14897 now reuses the standard rotation handlers and locally works fine

**Comment by theboomr** [comment]
Not sure if I should just comment here or open an issue report, but I'm running the latest nightly as of right now (10.104) and I'm still seeing the same old behavior on my Pocketbook Era Color, where rotation gets inverted after the device goes to sleep and wakes back up :/

**Comment by jannickfahlbusch** [comment]
I only implemented this for the PB700 so far since I don't own the other devices to test the behavior.
I've submitted https://github.com/koreader/koreader/pull/14904 to apply the fix also on the Era color.

@grabi678 also reported the issue on the Inkpad color - however since I don't know which of these is the affected devices I'd like to be careful to not break any existing functionality

**Comment by Biep** [comment]
So far here all seems to work well.  Thank you so much!

A small remark on the code:
```
 local target_rotation
        if current_orientation == 0 then
            target_rotation = 0
        elseif current_orientation == 2 then
            target_rotation = 1
        elseif current_orientation == 3 then
            target_rotation = 2
        elseif current_orientation == 1 then
            target_rotation = 3
        end
```
Isn't that a bit ugly - writing out a mapping line by line?  I'd have done something like - barring syntax errors (it was long ago I wrote Lua) and stupid mistakes:
```
target_rotation = {0, 3, 1, 2}[current_orientation]
```

**Comment by Frenzie** [comment]
You'd have to split up the assignment and the accessing, but yes, you can do that.

**Comment by Mido-Vodella** [comment]
I don't know if this is the appropriate place to post this, but my Era has just recently begun having this exact issue. I am currently running version 2026.03 and have disabled all custom patches and plugins in an attempt to resolve, but have thus been unable to.

**Comment by Frenzie** [comment]
If it's one of these devices that would suggest the fix proposed here had the result of breaking it for you. A new issue with the full info (also firmware version and such) would probably be simplest to get all the required info since it methodically asks for it.
https://github.com/koreader/koreader/blob/8def50f2187ff32649dd7ecec786253d60c9937b/frontend/device/pocketbook/device.lua#L703-L726

**Comment by pivnymag** [comment]
> Yes, it'll be in today's nightly.

Oh, thank you so much for fixing this issue! I've given up on Koreader and unhappily went back to the slower Pocketbook software just because of the inconsistent rotation problems and now I am gladly back!
