### ISSUE TITLE
Q: How to use custom multiswipe

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11224]
KOReader version: v2023.10-41
Device: Kindle Scribe

Hey guys,

Any advice on how to properly set up custom mulswipes?

I tried multiple times, here are the outcomes:
1) I click `Record multiswipe`, then a dialog with input text shows up, that is asking to reproduce a multiswipe.
2) I do a multiswipe, let's say, diagonal to bottom-left, then backwards to top-right.
Most of the time, this dialog window just moves.
3) Sometimes, arrows in the text input field show up, but that's very rare.

What if I would like to draw a shape, like `W`?
It feels quite finicky

**Comment by jonnyl2** [comment]
You have to draw the gesture outside of the dialog box for it to register and to prevent moving the box.

Recognition of gestures works better on some devices than others -- probably not KOReader's fault. 

- Often, diagonal moves are misinterpreted as 2 moves, e.g. southwest as west+south. You just have to keep trying.
- Drawing longer lines often helps with recognition IME
- Note that you can't mix diagonal moves with straight moves (that's one thing I was a bit perplexed by when I first set them up)

I haven't had any issues drawing a `W` multigesture on my Kobo. At one point I was using that for Wifi toggle.

**Comment by Frenzie** [comment]
I realize that I wrote the functionality, but I'm not sure what to say other than just draw a w. :blush: You need to make sure your swipes are sufficiently large as jonnyl2 said.

https://github.com/koreader/koreader/assets/202757/2650ed70-6b10-4735-bea3-2d39687fc2e4

> Note that you can't mix diagonal moves with straight moves (that's one thing I was a bit perplexed by when I first set them up)

Trying to mix them doesn't work well because then instead of a convenient quick gesture you have to be impossibly (or perhaps rather, annoyingly) precise. That way the gestures you actually make can be less well defined so you only have to bother with sufficient precision for the first leg, making it significantly more convenient to use.

**Comment by jonnyl2** [comment]
>Trying to mix them doesn't work well because then instead of a convenient quick gesture you have to be impossibly (or perhaps rather, annoyingly) precise. That way the gestures you actually make can be less well defined so you only have to bother with sufficient precision for the first leg, making it significantly more convenient to use.

That makes sense and I figured this was the reason. Perhaps this constraint could be mentioned in the help text or dialog box to preempt any frustration for new users trying to draw an "N" for example ;)

**Comment by mergen3107** [comment]
Thanks! 
Yes, I start drawing outside the window, but then the window ends up moving once I lift my finger. 

That's a bummer that you can't mix straight and diagonal line though.

**Comment by mergen3107** [comment]
Thank you @Frenzie for the video!

I might be quite slow compared to you, maybe that's the reason :D

**Comment by NiLuJe** [comment]
> I might be quite slow compared to you

I don't recall if that's a concern in this specific context, but it might (e.g., you might be effectively doing *pans* instead of swipes).

**Comment by mergen3107** [comment]
Interesting! 
I am sure each recording I start outside the box, and yet it ends up moving sometimes

**Comment by Frenzie** [comment]
For the record, the dialog does not get in the way of multiswipes and it does not need to be avoided. If you're moving it you're panning rather than doing a multiswipe.

It's probably better to not have it movable to prevent confusion but that won't help otherwise.

**Comment by mergen3107** [comment]
> If you're moving it you're panning rather than doing a multiswipe.

This is still weird. Panning of the container sometimes starts when first tap is outside the container frame.

From other news, I was able to do W with shorter distances and wuicker movement. Tested in opening screensaver, works good!

However, I couldn't do the upside-down W. 

@NiLuJe 
When I open the cover, I see the message about secret gesture. 
I then flip the device, the message goes away and frontlight stays on, as we discussed before. 
However, when there is no message and gesture-unlock is not working neither, unless I recycle power on/off with cover or the button.

1) Can it be made so the message can be brought back by a tap?
2) Alternatively, can you allow the screen unlock gesture to work without the message?

**Comment by jonnyl2** [comment]
>However, I couldn't do the upside-down W.

Have you tried doing it flatter? So instead of `/\/\`, do 

<img width="179" alt="image" src="https://github.com/koreader/koreader/assets/95502269/fb639b9b-6b21-492d-a50e-969562cbef95">

**Comment by mergen3107** [comment]
@jonnyl2 
Thanks! That helped :D 
It took me some time to calibrate myself, now I can open screensaver in 4/5 cases lol

**Comment by NiLuJe** [comment]
> 2\. Alternatively, can you allow the screen unlock gesture to work without the message?

It... already does? The message is irrelevant to the actual functionality.

**Comment by mergen3107** [comment]
Oops, sorry! You are right. It works!
It must have been my bad time calibrating to the multiswipe gesture. Regular one works OK each time, multiswipe still takes me a few attempts, but eventually works too :D

**Comment by mergen3107** [comment]
Alright, I think custom multiswipes work great! I got used to them, and now I use them everyday to unlock KOReader. First, I used them with a backup gesture in parallel, but now I am sure I can reliable do that custom multiswipe from a first try :D 

Just in case, how could I gracefully stop KOReader from SSH? I have usbnet enabled all the time.
Is `killall koreader.sh` good enough?

**Comment by Frenzie** [comment]
I'm not sure if that's handled gracefully right now, depending on your
definition of gracefully.

**Comment by mergen3107** [comment]
By "gracefully" - I mean in the same way as if KOReader was exited by the top menu `Exit` button. So then all necessary things are restored, on Kindle these `awesome`, `pillow`, password, iptables, etc...

**Comment by Frenzie** [comment]
I'd say give it a try and see. It might differ on a platform basis. But I suspect it could be handled better.

**Comment by mergen3107** [comment]
OK, so:
`killall reader.lua` is the command to kill KOReader. However, Kindle becomes the same slow as it did when Terminal Emulator crashed #11229 .
In other crashes, Kindle usually stayed responsive. So it was interesting to see Kindle slow down with Terminal emulator crash.

For graceful avenues, I can see that main loop is here in `koreader.sh` (L321-L328):
```
RETURN_VALUE=85
while [ "${RETURN_VALUE}" -eq 85 ]; do
    # Do an update check now, so we can actually update KOReader via the "Restart KOReader" menu entry ;).
    ko_update_check

    ./reader.lua "$@" >>crash.log 2>&1
    RETURN_VALUE=$?
done
```

Is there a way to override this `RETURN_VALUE`? I tried `export RETURN_VALUE=1`, but it didn't help.
`RETURN_VALUE` isn't exposed at all, it is a null string from `echo $RETURN_VALUE` when KOReader is running.

**Comment by mergen3107** [comment]
This slowness of Kindle is fixed when you start KOReader again and exit via Top menu.

**Comment by Frenzie** [comment]
> Is there a way to override this RETURN_VALUE? I tried export RETURN_VALUE=1, but it didn't help.

Right, so on SDL that returns 0 because it's handled and shuts everything down properly, while on Kindle that wouldn't be handled as I suspected but testing is the quickest way to tell. (Also in that case it wouldn't save your settings/reading progress.)

I'm a bit confused though. You presumably wouldn't get 0 but you should presumably still get something that doesn't happen to be 85?

**Comment by NiLuJe** [comment]
You'll never get a graceful exit (as in, saved settings) when killed by a signal, we don't have a signal handler for any of them (nor should we, signals are hell).

**Comment by mergen3107** [comment]
Thank you for explaining!

> I don't recall if it persists while inside KOReader, though, but I suspect it wouldn't

I've yet to see this inside KOReader :)

**Comment by mergen3107** [comment]
Alright, thanks everyone! 

The OP questions are now all answered, closing this ticket.

**Comment by Frenzie** [comment]
> You'll never get a graceful exit (as in, saved settings) when killed by a signal, we don't have a signal handler for any of them (nor should we, signals are hell).

That's not true, we do on SDL. ;-)

**Comment by NiLuJe** [comment]
IIRC, that's because we piggy-back on Alt+F4 and/or SDL's own signal handler.

**Comment by Frenzie** [comment]
Correct, I wrote that in.

**Comment by mergen3107** [comment]
Interesting note about Exit screensaver gesture.

I found out why I couldn't unlock with a custom multiswipe many times when I started using it. 

It turns out, FM and Reader have their own sets of gestures. That includes Exit screensaver gesture as well. 

First I added this custom multiswipe in Reader gestures only, having another one as a backup. FM only had the backup one. And of course I couldn't unlock KOReader with custom multiswipe, if KOReader was locked from FM. I paid no attention where from I locked KOReader for testing.

Then I removed the backup gesture. Then it turned out that I didn't have any gestures to Exit screensaver. So KOReader just said, welp no gesture is set up, tap to unlock.

**Comment by Frenzie** [comment]
Ah, right. Many gestures are exclusive to one or the other but this is probably a scenario that can or should be handled. Always showing a popup asking to apply it to both seems a bit unfortunate though.

**Comment by NiLuJe** [comment]
The code *should* be detecting this properly (i.e., showing the "tap" fallback if you only have it set in one view).

I haven't double-checked that in a while, but I vaguely recall it working when it was originally implemented, I think.

**Comment by mergen3107** [comment]
Yes, ultimately it did detect and said "no gesture detected, tap to unlock". 

I just didn't realize it, because I first set the first gesture in both FM/Reader (and forgot). Then added custom gesture in Reader only, and went to test it after locking in FM as well. So I didn't catch that I didn't add the custom gesture in FM as well, treating these failures as false negatives (like, oh, custom gesture doesn't work).

**Comment by yogi81** [comment]
I have created a small koreader screenlock plugin which works for me:
https://github.com/yogi81/screenlock_koreader_plugin
