### ISSUE TITLE
FR: Remove deleted books from collections

### ISSUE THREAD

**Issue by Thiago-Morais** [koreader/koreader#14009]
**Does your feature request involve difficulty completing a task? Please describe.**
When you delete a book, it remains in all previous collections.
This is great if you want to add the same book again or want to keep the collection data for some reason. But most of the time, when you delete a book, you have no use for them in the collections.

**Describe the solution you'd like**
There should be a way to clear all deleted books from a collection or all collections.
Also, an option to auto remove deleted books from its collections, like there is with the history (`Auto-remove deleted or purged items from history`)

**Describe alternatives you've considered**
Right now, if you want to remove deleted books from the collections, you have to manually remove each book from each collection one by one.

1. Remember each book you deleted
2. Remember what collection they were in 
3. Go to each collection
4. Remove the book from the collection
5. Do that for every collection, for every deleted book

**Comment by hius07** [comment]
If you delete a book via long-press - Delete, it is removed from all collections immediately.

**Comment by Thiago-Morais** [comment]
Oh, I experienced this issue with wallabag's plugin so I belive it is a plugin only issue

Should I create a new issue then?

**Comment by Frenzie** [comment]
Could you clarify how this issue occurs with the Wallabag plugin?

**Comment by antistic** [comment]
I also have this problem when I delete from outside of KOReader. I'm not using the Wallabag plugin, but maybe it's doing something similar.

It would be great to have a button to remove deleted books from the collection instead of remembering that I have to delete from within KOReader.

**Comment by hius07** [comment]
Collections do not show deleted books.

**Comment by antistic** [comment]
Steps to reproduce collections showing deleted books:

1. Add book to a collection
2. Delete the book file outside of KOReader (e.g. manually via the file manager or automatically via SyncThing or possibly via the wallabag plugin)
3. View collection. The book is still visible. If you try opening it, it will display the error "File X does not exist", and remain visible in the collection.

This happens for me on version 2025.04, on both Android and Linux.

**Comment by hius07** [comment]
Looks like you do this while KOReader is running? We scan the storage on program start only.
Restart the program, the book should be absent in the collection.

**Comment by hius07** [comment]
For sure, if you delete a book via the KOReader UI, it should be removed from collections.
If the Wallabag plugin doesn't do this, it should be fixed.

**Comment by liskin** [comment]
`Wallabag:deleteLocalArticle` calls `FileManager:deleteFile` which updates both history and collections, so I don't think this should happen when the book is deleted via the Wallabag plugin. Can you still reproduce it in current KOReader?

(and if yes, can you pls clarify the exact sequence of events including why the book gets deleted - is it because it's marked as finished, or is it because it got archived on the Wallabag server, or something else? Is it perhaps still open when it's being deleted?)
