### ISSUE TITLE
[Kindle] Cannot enter after a sleep

### ISSUE THREAD

**Issue by NoAnyLove** [koreader/koreader#1867]
- KOReader version: nightly-20160227
- Device: Kindle Paperwhite 2
#### Issue

I'm using a KPW2 with special offers, so I need to swipe the screen to wake it up. I can wake up the device by open the smart case or press the power button, and the screen will light up. But I cannot enter the system, because the swipe seems doesn't work.

I guess this issue may be related to issues#1862, because loosing touch input can cause the same issue.
#### Steps to reproduce

with special offers eidtion,

sleep
wake
swipe the screen to enter

Note, You have to long-press the power button, and hit Cancel button to enter the kindle.

**Comment by NiLuJe** [comment]
Which FW version, and how do you launch KOReader?

(And, no, completely unrelated to #1862, that one is squarely in Kobo's camp).

Try with the latest OTA, this is probably fixed by #1861

**Comment by NoAnyLove** [comment]
I'm using FW 5.6.5, and lauch KOReader through kpvbooklet.

I just tried launch KOReader through KUAL, and it seems doesn't have this issue.

**Comment by NiLuJe** [comment]
Does this still happen with recent nightlies/OTA?

**Comment by NoAnyLove** [comment]
Hi NiLuJe,

I tried the recent released koreader-nightly-20160323, it still happen if the KOReader is lauched from kpvbooklet.

**Comment by NiLuJe** [comment]
The only SO device I have is a PW1, which doesn't run FW 5.6.5 (and which I don't have in my household right now anyway), so this is going to be tricky to test...

One question though: you're supposed to keep the native status bar when using KPVBooklet right? Because I'm fairly sure I broke that by stopping the WM.

**Comment by NoAnyLove** [comment]
I'm not sure about this question. It seems that KPVBooklet doesn't have a graphic user interface. And after lauching KOReader, no matter from KPVBooklet or from KUAL, it's aways full-screen, so the native status bar is invisible, I think.

**Comment by NiLuJe** [comment]
Right, good.

Then, yeah, I don't really know what's going on, and I'm not familiar enough with KPVBooklet to psychic debug this one ;).

**Comment by robert00s** [comment]
@NoAnyLove Can you try with latest version? I have KPW3 with SO and KPW2 without SO and I don't have problems like you.

**Comment by NoAnyLove** [comment]
@robert00s I have tried the latest release koreader-nightly-20170821, it still cannot unlock the screen if I launch koreader via KPVBookelet.

**Comment by robert00s** [comment]
Strange. Do you have still FW 5.6.5? I have 5.8.7 so maybe you should upgrade your kindle :)

**Comment by NoAnyLove** [comment]
I'm currently use 5.7.4
