### ISSUE TITLE
Save history file when highlighting

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2258]
- KOReader version: 2015.11-587
- Device: Kobo Glo
#### Issue

As I understand it, the "metadata.epub.lua" for a book, is updated when closing koreader or opening another book.
The problem is that, sometimes, after I read a big part of a book and highlight a lot of mistakes for later fixing, the koreader would crash and all these highlights are gone for ever!
After that I have to re-read the same part, which I don't!
It has happened to me a few times and I wonder if we could have an option to save the changes to the file when they occur, or after a page turn, or whatever, but more frequently...

edit: re-checked with 2015.11-587, no change.

**Comment by Hzj-jie** [comment]
There is a setting DAUTO_SAVE_PAGING_COUNT for this functionality. You can create a defaults.persistent.lua in the koreader/ folder, add DAUTO_SAVE_PAGING_COUNT = {an integer value} to control the frequency to save the metadata and other settings. The integer value indicates the count of page turns between two auto-saving attempts.

**Comment by Hzj-jie** [comment]
p.s. I have Kobo Aura HD and Kindle Voyage, both with KOReader installed. Segment failure are fairly common on Aura HD, but KOReader never crashes on Kindle Voyage. @houqp also mentioned he rarely noticed crashes on Kobo Aura H2O. So the crash is more like a Kobo stock software issue.

**Comment by houqp** [comment]
When it crashes, please report the issue with crash.log if you can ;) It will help us stablize the reader. For now, DAUTO_SAVE_PAGING_COUNT is the closest thing you can get. 

In the future, the settings module will be redesigned so all state changes of the book will be saved to disk immediately. This way, koreader will always be able to recover from crashes.

**Comment by embryo10** [comment]
Thank you, I'll try that.
BTW there is a typo at the comment of this parameter in the defaults.lua:
antomatically should be automatically

**Comment by houqp** [comment]
Good catch, @embryo10, I have corrected it in my PR :)

**Comment by Hzj-jie** [comment]
That's indeed a very uncommon typo; I cannot quite imagine a u-n typo. Is it intentional?

**Comment by houqp** [comment]
It's probably not intentional, at least I can't think of any reason ;)

**Comment by Frenzie** [comment]
Various alternative keyboard layouts (e.g., Colemak) keep U where it is in QWERTY but stick N in the position of H or J. Then again, I still can't imagine such a row-spanning typo.

**Comment by poire-z** [comment]
> The problem is that, sometimes, after I read a big part of a book and highlight a lot of mistakes for later fixing, the koreader would crash and all these highlights are gone for ever!

Corrupted/empty settings on crash/freeze should hopefully no more happen - and losing settings and annotations should now be limited to losing 15mn of annotations & page progress (that one can reduce to 5mn via the menu), thanks to #5678 and #5687 (January 2020).
