### ISSUE TITLE
Crash while scrolling PDF on NGP

### ISSUE THREAD

**Issue by EugeneLoy** [koreader/koreader#2398]
* KOReader version: v2016.11.20-nightly, also can confirm the same issue for prev. nightly build
* Device: Nook Glowlight Plus

#### Issue

Crash while scrolling.

#### Steps to reproduce

Open PDF, scroll a few pages -> application crash.

I am attaching the specific document I used to reproduce the issue but I have found that it crashes on nearly all pdfs I tried (have not tried other types of docs yet).
I am not doing anything in the app except opening document and then scrolling few times.
I have not identified specific page or number of times you need to scroll (although it rarely takes more than 10-20 gestures) that lead to crash.
I am also attaching logcat dump.

Can provide more info if you need something specific, also I am ok with helping to debug the issue.

[logcat dump](https://github.com/koreader/koreader/files/628358/1.txt)
[document](https://github.com/koreader/koreader/files/628359/A-novel-approach-to-on-line-handwriting-recognition-based-on-bidirectional-long-short-term-memory-networks.pdf)

**Comment by houqp** [comment]
@EugeneLoy , you are not running the latest version. The line 657 indicated in the crash log does not exist in the lastest code base right now. 

It looks like a bug that could have been fixed by my recent commit: https://github.com/koreader/koreader/commit/cd24eb82d7de56fe9e64d2e506815b02d0694ee3

In fact, I don't even know KOReader runs in NOOK. Did you install it using the apk? You should be able to find the exact version from the top touch menu under the pokeball tab. The latest one right now is: v2015.11-728-g64a79f6/

**Comment by EugeneLoy** [comment]
@houqp 

> In fact, I don't even know KOReader runs in NOOK. Did you install it using the apk?

The device runs Android 4.4.2, so, yes. I used [this one](https://github.com/koreader/koreader/releases/download/v2016.11.20-nightly/koreader-android-arm-linux-androideabi-v2015.11-696-g2bc7b01.apk) , listed in nightly builds.

> You should be able to find the exact version from the top touch menu under the pokeball tab.

It reports `v2015.11-696-g2bc7b01`

> The latest one right now is: v2015.11-728-g64a79f6

Do you have this apk build published somewhere? If not I'll try to build it on my own but not sure how much time will it take for me to do this.

I'll come back with test results as soon as I try it out.

**Comment by KenMaltby** [comment]
http://build.koreader.rocks/download/nightly/

**Comment by EugeneLoy** [comment]
I tried `v2015.11-728-g64a79f6` build.
Can confirm that issue is still there.
Here is [logcat dump](https://github.com/koreader/koreader/files/629014/2.txt).

**Comment by houqp** [comment]
This time it's a different crash: 

```
I/KOReader(16494): # hinting page 5

F/libc    (16494): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 16507 (reader.launcher)

I/imx6.gralloc( 2034): update_to_display:left=0, top=0, right=1448, bottom=1072 updatemode=5

I/DEBUG   ( 2033): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   ( 2033): Build fingerprint: 'NOOK/ntx_6sl/ntx_6sl:4.4.2/KOT49H/42.1.45_user:user/release-keys'

I/DEBUG   ( 2033): Revision: '393728'

I/DEBUG   ( 2033): pid: 16494, tid: 16507, name: reader.launcher  >>> org.koreader.launcher <<<

I/DEBUG   ( 2033): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000

I/DEBUG   ( 2033):     r0 65dd4be8  r1 6f270d78  r2 66f06b58  r3 6a5e0af0

I/DEBUG   ( 2033):     r4 65dd4850  r5 66f01ba0  r6 66f176d8  r7 00000888

I/DEBUG   ( 2033):     r8 66fce648  r9 6f2b34b0  sl 6f270cf0  fp 00000888

I/DEBUG   ( 2033):     ip 66f1a120  sp 6a5e0a98  lr 68434e44  pc 00000000  cpsr 600f0010

I/DEBUG   ( 2033):     d0  3ff0000000000000  d1  3ffc76f31219dbcc
```

Looks like a NULL pointer bug in C code while it's hinting page 5. Does this crash still happen with all your PDFs?

**Comment by EugeneLoy** [comment]
Just tried it on 2 other PDFs and on FB2. Getting crash on all of these. Can upload logs\docs if you need it.

**Comment by houqp** [comment]
Yes, I want to see if they all have the same stack trace. How about djvu files?

**Comment by EugeneLoy** [comment]
I have reproduced the issue few times with `pdf` `txt` and `fb2` files and collected logs.
I also tried to open `djvu` but got message saying that file engine is not supported. 
This might be a chance but it feels like it takes more time to crash app with `txt` than with `pdf` and `fb2` btw (not longer than a minute anyway).

Files I used:
[aaas.txt](https://github.com/koreader/koreader/files/632183/aaas.txt)
[16-HungarianRings.pdf](https://github.com/koreader/koreader/files/632184/16-HungarianRings.pdf)
[cathedralandbazaar.fb2](https://www.dropbox.com/s/w9gq2hwj97syrmf/cathedralandbazaar.fb2?dl=0)
[code_complete.djvu](https://www.dropbox.com/s/p0vj63dthcd5j40/code_complete.djvu?dl=0)

Logcat dumps:
[djvu_1.txt](https://github.com/koreader/koreader/files/632173/djvu_1.txt)
[fb2_1.txt](https://github.com/koreader/koreader/files/632177/fb2_1.txt)
[pdf_3.txt](https://github.com/koreader/koreader/files/632174/pdf_3.txt)
[pdf_4.txt](https://github.com/koreader/koreader/files/632175/pdf_4.txt)
[txt_1.txt](https://github.com/koreader/koreader/files/632178/txt_1.txt)
[txt_2.txt](https://github.com/koreader/koreader/files/632176/txt_2.txt)

**Comment by houqp** [comment]
Looks at the crash log, they are all different crashes. At this point, it doesn't look like bug in the code since other platforms do not crash like this. It looks like toolchain issue to me. Does nook have its own toolchain?

**Comment by Frenzie** [comment]
Closing due to lack of activity.
