### ISSUE TITLE
Screensaver conflicts with Kindle default screensaver

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2848]
* KOReader version: latest nightly
* Device: KT3

#### Issue
I have a KT3 without SO and have trouble with the default screensaver conflicting with the Koreader cover page.

I want the cover page but sometimes the Kindle screensaver is rendered after, or is rendered on resume.
#### Steps to reproduce
1. Turn on cover screensaver.
2. Press power button on KT3

**Comment by houqp** [comment]
unfortunately, I don't own kindles anymore. @robert00s, are you able to reproduce this?

**Comment by Hzj-jie** [comment]
Yes, I can confirm this issue happens also on my Kindle. (Though I do not really care :)

**Comment by Frenzie** [comment]
It's probably what I mentioned back when the screensaver was implemented (first it's drawn and only a while later the actual standby is called, so maybe the Kindle screensaver sometimes overwrites)

**Comment by slow-mo** [comment]
I've noticed this issue on my PW2 too.

**Comment by ersi-dnd** [comment]
The solution should be to provide more options for screensavers. E.g.

- First page (as is now)
- Current page/view
- Blank
- Random image

**Comment by z3t0** [comment]
Well I think the first part of the solution is to disable the Kindle screen saver when using calibre's own screensaver

**Comment by ersi-dnd** [comment]
@z3t0 

Yes, if Kindle has that option. Does ads-supported Kindle have it?

With an earlier Koreader version in my Pocketbook I also experienced double screensaver and the solution was to put Pocketbook's screensaver to blank, but probably not every e-reader has that. To me it's sort of obvious that Koreader should also have an option for blank screensaver.

**Comment by diegombeltran** [comment]
Hi, is this working? Just updated to the last nightly on my PW1-ad-free and realized there's no screensaver option. Also, it wasn't working before the update (It was showing the default screensaver)

**Comment by NiLuJe** [comment]
Yep, known issue.

**Comment by slow-mo** [comment]
Hi NiluJe, it's the last downgradable version, maybe 5.4.5? I don't have the kindle with me at the moment, I'll tell you for sure this evening.

**Comment by NiLuJe** [comment]
Don't rush, I won't have time to properly look into this for a while, it's just so that I have all the background info for when I do ;).

**Comment by slow-mo** [comment]
Ok, I didn't rush 😄 Btw the FW version is 5.4.5.1 as I recalled.

**Comment by NiLuJe** [comment]
I can't reproduce on my PW2, probably for a good reason.

(It's running FW 5.8.1, and we SIGSTOP awesome on FW >= 5.7.2, so the system never draws the default screensaver).

Unfortunately, I don't have access to my PW1, so I can't double-check if lowering the FW version for this specific bit of workaround is safe...

**Comment by NiLuJe** [comment]
Turns out we were playing with awesome for pretty terrible reasons, so, hopefully, this'll be fixed.

**Comment by slow-mo** [comment]
Nope. Just installed the last nightly but the issue is still there. The screensaver plugin was working fine before those new features for random image, reading progress etc. though.

**Comment by slow-mo** [comment]
I can't tell the exact nightly, but I just tried koreader-beta-20180602 and it's working, whereas koreader-beta-20180729 isn't working, so it must be something in between.

**Comment by Frenzie** [comment]
Thanks, even that should be helpful already!

**Comment by slow-mo** [comment]
Thank you guys!

**Comment by NiLuJe** [comment]
Can't reproduced on my end after #4336 (before that, I couldn't tell, I was running the cblitbuffer, which doesn't support SS on Kindle, and after that, the latest nightly, which I broke with #4324 :D)

**Comment by slow-mo** [comment]
I'm not sure I got it right, is https://github.com/koreader/koreader/pull/4336 supposed to fix the screensaver issue too?

**Comment by NiLuJe** [comment]
Yes, and it should have made it to today's ota (-24).

**Comment by slow-mo** [comment]
So I'm afraid it's not working, damnit :(

**Comment by NiLuJe** [comment]
Can't reproduce here, which FW are you running? And I'm assume this is of
course not a SO device...

**Comment by slow-mo** [comment]
It's a Kindle PW2 firmware version 5.4.5.1, and it is not a special offers device.

**Comment by slow-mo** [comment]
@NiLuJe editing line 198 doesn't help.
I tried to use koreader.sh from koreader-beta-20180602 (which is the build that is working for me) and it doesn't fix the issue. So maybe the problem is not there?

**Comment by NiLuJe** [comment]
Spidey-sense tingling... How are you running KOReader?

**Comment by slow-mo** [comment]
Wait wait wait, I rebooted my kindle and now it seems to work both launching koreader via KUAL and KPV Booklet.
It's late now, but if it's of any interest tomorrow in the morning I can see if it's https://github.com/koreader/koreader/pull/4336 that fixes the issue after a reboot or FW_VERSION="5.8.0".

**Comment by slow-mo** [comment]
I spoke too soon. At first koreader's screensaver was prevailing after the reboot, but then I tried exiting koreader, putting my kindle in standby (so => system screensaver), waking it up, starting koreader again and now the system screensaver is overtaking half the screen again.

As for your question @NiLuJe, I'm trying to run Koread both via KUAL an KPV Booklet.

**Comment by NiLuJe** [comment]
That was going to be my next question: stuff will probably break with KPVBooklet on subsequent startups.

Stuff *should* always work through KUAL, as long as you've never launched it once via KPVBooklet in that power cycle.

I have *no idea* what the original purpose of that "count the amount of time KPVBooklet started" check, so don't ask me why ;).

I've never used KPVBooklet on my end, which also explains why I couldn't reproduce it (once I fixed other related issues, that is ;p).

**Comment by NiLuJe** [comment]
Rabbit holed it: https://github.com/koreader/koreader/commit/60f83e842ccce57931cbed5ffcebb28515f6f5d7

So, err, reasons, I guess? :D.

**Comment by NiLuJe** [comment]
Best I can do is make sure running from KUAL will never be affected by KPVBooklet (#4342).

**Comment by slow-mo** [comment]
Regarding https://github.com/koreader/koreader/pull/4336, I can confirm that it doesn't fix the issue, even if you never used KPV in that power cycle.  It's forcing FW_VERSION="5.8.0" that works.

As for KPVBooklet, I guess I can live without it. In fact since we have the cover browser plugin I rarely exit koreader.
