### ISSUE TITLE
Crash on start whith version v2015.11-1058-g53eb4de

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2961]
* KOReader version: v2015.11-1058-g53eb4de
* Device: Kobo Glo HD

#### Issue
When I try to run koreader, nothing happens.
Here are the traces on the crash.log file:

```
06/15/17-11:10:51 ERROR cannot open translation file: l10n/en_US/koreader.po
./luajit: frontend/device/generic/powerd.lua:63: assertion failed!
stack traceback:
	[C]: in function 'assert'
	frontend/device/generic/powerd.lua:63: in function 'frontlightIntensity'
	frontend/device/kobo/powerd.lua:48: in function 'setIntensityHW'
	frontend/device/generic/powerd.lua:38: in function 'turnOffFrontlightHW'
	frontend/device/generic/powerd.lua:27: in function 'new'
	frontend/device/kobo/device.lua:128: in function 'init'
	frontend/device.lua:39: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/horizontalgroup.lua:1: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:1: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:91: in main chunk
	[C]: at 0x00013e85
```

**Comment by Eduardomb22** [comment]
Having the same problema with Kindle pw3

**Comment by Hzj-jie** [comment]
Covered by change https://github.com/koreader/koreader/pull/2962.

**Comment by Hzj-jie** [comment]
This should be fixed. Would you mind to try it again?

**Comment by Brnoch** [comment]
Yes, fixed by the new version. Thanks !

**Comment by Hzj-jie** [comment]
Sorry for the trouble :(

**Comment by Brnoch** [comment]
On my Kobo there's still a problem as the light status isn't updated. It
always displays "L: Off"
