### ISSUE TITLE
Incorrect illumination percentage in the status bar

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2970]
* KOReader version: 2015.11-1062
* Device: Kobo Glo HD

#### Issue
On my Kobo, when the light is set to 1%, the status bar displays "L: Off"

**Comment by a-kohout** [comment]
Related #2973 #2941

**Comment by Hzj-jie** [comment]
I believe this has been fixed already. Would you mind to try the latest version?

**Comment by Brnoch** [comment]
I tried to make it OTA, but it keeps saying that Koreader is up to date on
my Kobo.

2017-06-24 3:04 GMT+02:00 Hzj_jie <notifications@github.com>:

**Comment by Frenzie** [comment]
Sorry about that, Gitlab changed some stuff.

**Comment by a-kohout** [comment]
Still broken in `v2015.11-1071-g970f2e7`, Off and intensity 1 reads as "L: Off"

**Comment by Frenzie** [comment]
Do you mean "*On* and intensity 1 reads as "L: Off""?

**Comment by a-kohout** [comment]
No, if the light is off it reads correctly as "L: Off"
With the light on at level 1 it still reads as "L: Off"
Levels 2 and up read correctly

**Comment by Brnoch** [comment]
Not quite the same on my Glo HD.
The status remains always "L: Off"
I can't switch the light off with a swipe (even if the message saying that the frontlight has been disabled appears)
When I click on the "Frontligh" button, the light goes automatically to the minimum value whatever the value was before. And the displayed value is "0".

**Comment by a-kohout** [comment]
Weird that you're getting a different behavior.
I can only swipe the light off from a level that doesn't say "L: Off", which for me is 2 and above.
I reported what you're describing in #2974.

**Comment by Hzj-jie** [comment]
@Brnoch the update server is back, would you please try the latest version? I do not have a Glo HD, but this behavior does not happen on my Aura HD.

**Comment by Brnoch** [comment]
I just tested the new version. The problem is still the same.
On the frontlight panel, the buttons don't work everytime but I can't find
in which sequence they don't.

2017-06-27 6:55 GMT+02:00 Hzj_jie <notifications@github.com>:

**Comment by Hzj-jie** [comment]
Is one of the four issues I have mentioned in https://github.com/koreader/koreader/issues/2974 the same as yours?

**Comment by Brnoch** [comment]
Made the test with the latest version: it seems that nothing changed.

@Hzj-jie I observe this:
_If frontlight is off, restarting KOReader will turn on the frontlight then turn it off, i.e. flashes._ > No, I have no flashing...
_Once frontlight is off, opening frontlight menu will turn on the frontlight at level 1._ > Yes, that's the case on my device too.

**Comment by oldhasbeen** [comment]
I have that 1% light with front light off issue as described by a-kohout since a very long time on my H2O. currently on 1107.
Any progress on this?

**Comment by poire-z** [comment]
Before commiting this change, could some of you test this change mentionned at https://github.com/koreader/koreader/issues/3103#issuecomment-323662002 by manually updating a file on your devices:

https://github.com/koreader/koreader/blob/1f75bc645ca6640f951ce4d0103be251a590bb00/frontend/device/kobo/powerd.lua#L8-L10

Change `fl_min = 1` to `fl_min = 0`.
This seem to fix the 1% acting as off, and the status bar report of that (with occasionaly it saying 0% instead of Off).
(Please check that sync of level and state (on/off) is working correctly between nickel and koreader, if you use that feature - i can't test that.)

**Comment by oldhasbeen** [comment]
@poire-z 
I have done that change. Used is H2O 1st ed. Synchronizing with nickel fronlight works ok for me. Have changed levels five times alternating in both (3 times 1% / 0%, then 10% / 0%  and 35% / 0% )  - Koreader and  Nickel - and switched to the other. Change in frontlight every time mirrored the change done in the other reader. 
I never use Nickel and have noticed now that the battery percentage in Nickel and Koreader seem not to synchronize well. I had 90% in koreader and after switching 77% in Nickel. Returning to koreader showed then 77% too.

**Comment by djalma2k** [comment]
Kobo Glo HD user here with 1152 version working flawesly rightnow.
I have had installed the 1055 one until yesterday when I upgraded koreader to 1152 version. Well, I suffered the OP's problem: status bar won't update the light status at all, not nickel syncronization either and koreader won't saved the light status when I closed it.
Well, I tried several options without results (only using the GUI) and I was going to try what @poire-z previously commented, but I did a last chance using the gui and the problem solved itself when I turn on the light pressing the left lower corner.
Regards.

**Comment by djalma2k** [comment]
@poire-z I tried your suggestion and still exists a bug.
1) Light is ON
2) Press "-1" button until zero. (At this time light is really OFF and status bar shows "0")
3) Press "Toggle" button (Light->0 and status bar shows "Off")
4) Press "+1" button to reach any value (Light is ON and status bar shows "Off")
Really it always happens when you press "toggle" button to disable light and then you press "+1" or "-1". But I show it this way to point that zero condition seems to have 2 states which really from the user point of view should be only one.

On the other hand, without your suggestion (fl_min = 1), when you press toggle button to disable light, you still can press "-1" button and set negative light values. (The OP's problem is present)

Regards.

**Comment by Frenzie** [comment]
Should be fixed by #3143.
