### ISSUE TITLE
[Android] ABI and API requirements

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4471]
We ship builds for two android ABIs: armeabi-v7a and x86.
We target code for a minimum API of 9 (2.3)

Most devices running on API 9 (including the emulator) are using an older ABI (armeabi) so the program will crash in those devices (because luajit is built for an incompatible arch)

We have two solutions here:

- Add a target for android legacy devices (armeabi w/ minimum API 9).
- Bump requirements to API 14 (Android 4.0) where 99'9% of devices out there are using a compatible ABI.

TBH, I see no real gain in supporting old Android 2.3 devices and probably nobody is using them (we would see more issues here). I would suggest setting KOReader requirements to API14 and deprecatting launcher methods used in SDK < 11.

Skipping these older devices would allow us to refactor a bunch of old luajit-launcher code:

* Fullscreen/Viewport switching (just show/hide the statusbar when API > 16)
* Clipboard interface
* ...

**Comment by NiLuJe** [comment]
+1 ;)

**Comment by Frenzie** [comment]
I have no objections, but note that a legacy target may be hard to avoid. See #4348.

**Comment by Frenzie** [comment]
Also in that case I'd probably suggest migrating to the newest stuff (assuming 14 is still the minimum).

See https://github.com/koreader/koreader-base/pull/510#discussion_r139290793 about how to do 16, which is hopefully still the same. (Google keeps breaking things constantly...)

With any luck updating the Docker image would also be relatively uninvolved, but none of these are things I particularly want to put the effort into. ;-)

**Comment by pazos** [comment]
@Frenzie: a legacy target for the same ABI is fine imo.

> Also in that case I'd probably suggest migrating to the newest stuff (assuming 14 is still the minimum).

> See koreader/koreader-base#510 (comment) about some of that, which is hopefully still the same. (Google keeps breaking things constantly...)

> With any luck updating the Docker image would also be relatively uninvolved, but none of these are things I particularly want to put the effort into. ;-)

I will try to leave these things as they are. Things are working fine on API 14 (tested on emulator against ARM EABI v7a system image). I just need to remove deprecated methods (deprecating everything below API 11 - android 3) and try to simplify a little bit the launcher java code.

Any hint on why we're using runOnUiThread for things without UI (setBrightness, clipboard stuff...) ?

**Comment by Frenzie** [comment]
> Any hint on why we're using runOnUiThread for things without UI (setBrightness, clipboard stuff...) ?

To me that has always looked hugely overcomplicated but also harmless. I can only assume it's necessary.

> I will try to leave these things as they are.

That's quite incompatible with deprecating <14, at least from the Docker POV. ;-)

I (or someone, anyway) will have to build KOReader for Android in Docker to see why exactly the build is failing, but on the good side we know it's one of the commits in https://github.com/koreader/android-luajit-launcher/pull/90

**Comment by NiLuJe** [comment]
GitLab is being fussy on my end, but in the excerpts I'm seeing in the mails, it seems that it's outputting a bunch of unzip output on the NDK files? That seems utterly uninteresting and easy to send to the void ;).

**Comment by Frenzie** [comment]
That was probably from my slightly flawed first 0.2.0 image that I didn't test locally first. It should (and does) basically just get right to it.

**Comment by Frenzie** [comment]
The issue in question was this:
```diff
-echo 'export NDK=/home/ko/android-ndk-r12b' >>./.bashrc
+echo 'export NDK=/home/ko/android-ndk-r15c' >>./.bashrc
```

So the Docker image decided to download the NDK from scratch.

**Comment by Frenzie** [comment]
Ah, here's the problem for my new r15c Docker image. That's easy to fix.

```
android update project --path . -t android-19
Error: Target id 'android-19' is not valid. Use 'android list targets' to get the target ids.
make[2]: *** [local.properties] Error 1
make[2]: Leaving directory `/home/ko/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/home/ko/koreader'
Makefile:442: recipe for target 'update' failed
make: *** [update] Error 2
```

While I'm at it I should probably also check the error message in the r12 image. It'll only take another 20-30 minutes. /sigh

**Comment by Frenzie** [comment]
For good measure, here's the error on the old r12b image:

```
Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta3 /home/ko/koreader/platform/android/luajit-launcher/jni/luajit-build/armeabi-v7a/bin/luajit

make[3]: Leaving directory `/home/ko/koreader/platform/android/luajit-launcher/luajit-2.0'
ndk-build ANDROID_FULL_ARCH=armeabi-v7a
Android NDK: WARNING: APP_PLATFORM android-14 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml    
make[3]: Entering directory `/home/ko/koreader/platform/android/luajit-launcher'
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[armeabi-v7a] Compile thumb  : luajit <= android-main.c
[armeabi-v7a] Compile thumb  : android_native_app_glue <= android_native_app_glue.c
[armeabi-v7a] StaticLibrary  : libandroid_native_app_glue.a
[armeabi-v7a] SharedLibrary  : libluajit.so
jni/android-main.c:68: error: undefined reference to 'ALooper_pollAll'
jni/android-main.c:83: error: undefined reference to 'AAssetManager_open'
jni/android-main.c:89: error: undefined reference to 'AAsset_getLength'
jni/android-main.c:90: error: undefined reference to 'AAsset_getBuffer'
jni/android-main.c:102: error: undefined reference to 'AAsset_close'
jni/android-main.c:120: error: undefined reference to 'ANativeActivity_finish'
collect2: error: ld returned 1 exit status
make[3]: *** [obj/local/armeabi-v7a/libluajit.so] Error 1
make[3]: Leaving directory `/home/ko/koreader/platform/android/luajit-launcher'
make[2]: *** [apk] Error 2
make[2]: Leaving directory `/home/ko/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/home/ko/koreader'
Makefile:442: recipe for target 'update' failed
make: *** [update] Error 2
```

Anyway, no need to worry about that. I think I fixed up the r15c image now, fingers crossed.

**Comment by Frenzie** [comment]
@pazos Okay, we're back in business. All NDK < 15 and API <14 stuff can now be safely discarded without affecting the build.

**Comment by pazos** [comment]
> I (or someone, anyway) will have to build KOReader for Android in Docker to see why exactly the build is failing, but on the good side we know it's one of the commits in koreader/android-luajit-launcher#90

```
jni/android-main.c:68: error: undefined reference to 'ALooper_pollAll'
jni/android-main.c:83: error: undefined reference to 'AAssetManager_open'
jni/android-main.c:89: error: undefined reference to 'AAsset_getLength'
jni/android-main.c:90: error: undefined reference to 'AAsset_getBuffer'
jni/android-main.c:102: error: undefined reference to 'AAsset_close'
jni/android-main.c:120: error: undefined reference to 'ANativeActivity_finish'
```

It seems related to https://github.com/koreader/android-luajit-launcher/pull/90/commits/dbac4b39a69e785f2e471162b2aff2d64e2af8bb. Shall I revert that specific commit?

I spent a couple of hours yesterday trying to understand how we use Android. Some notes:

1 - Application never reaches onDestroy() once reader.lua is started. We have a [native method to finish the activity](https://github.com/koreader/android-luajit-launcher/blob/master/jni/android-main.c#L120) but is only called if luajit-launcher failed loading assets. We need to use ANativeActivity_finish on Device:exit() instead of letting Android to reap our dead window/app.

2 - Current [fullscreen switch](https://github.com/koreader/koreader/blob/master/frontend/ui/elements/screen_fullscreen_menu_table.lua) is broken. I think that can be easily fixed for old APIs (14-19?) and disabled on newer versions where it is not neccesary. It would be nice to restore last fullscreen setting when the application starts, but since it uses Device.screen and Device.input itself I'm not able to toggle  that setting at device initialization.

3 - We should probably [handle configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes), like orientation and size changes. Currently we rely on Android, which does onDestroy->onCreate, which is currently broken. This isn't mandatory for now but it is a must if we want to support rotation and other stuff (native keyboard, set a new viewport if the screen size changed...)

4 - Since debugging with standard tools on this kind of application is useless most of the time I think we should be more verbose logging on luajit-launcher (log current state and other override methods). Other things that we actually log don't make sense from the launcher POV (screen width, height, brightness).

5 - I modified a little bit our clipboard implementation. It seems to work but I'm unable to test it. How do I test if the clipboard works?. I can't find copy/paste anywhere on the UI.

**Comment by Frenzie** [comment]
> Shall I revert that specific commit?

Nah, then https://github.com/koreader/virdevenv/pull/30 and https://github.com/koreader/koreader-base/pull/792 would also have to be reverted. ;-) I was merely confirming it was indeed that commit that was the problem on r12b, while dropping it at the same time.

> I think we should be more verbose logging on luajit-launcher (log current state and other override methods). Other things that we actually log don't make sense from the launcher POV (screen width, height, brightness).

If you can easily insert sensible verbosity, go for it. ;-) (Or if not easily, go for it too if you have the motivation, hehe.)

> I modified a little bit our clipboard implementation. It seems to work but I'm unable to test it. How do I test if the clipboard works?. I can't find copy/paste anywhere on the UI.

You should be able to copy a text selection to clipboard from the highlight popup. I added that as an example clipboard implementation for people to expand upon. (Iirc there were some hacker complaints about adding the backend being difficult, but with the backend in place no one has expanded on it in front since. >_>)

But besides that iirc you'll have to stick some getClipboard calls in the code for testing the other side of the equation.

**Comment by pazos** [comment]
I can paste text on text editor with a long press. I'm still unable to copy text from KOReader, but copying text from other application and paste it on KO works great. Anyways, I'll leave clipboard unchanged for now. Without if/elsing SDK it doesn't look so bad.

**Comment by Frenzie** [comment]
Oh right, I forgot about that. Yup, you can paste with long press and copy with highlight.

**Comment by poire-z** [comment]
(small off-topic:)

> I added that as an example clipboard implementation for people to expand upon

Shouldn't we have a default internal clipboard available on all devices? So one can copy some book content, and paste it in other koreader InputText (there's not that many InputText, most useful would be to copy to the TextEditor).
Adding that very early in the generic Input dict seems to be enough and allows override by other devices:
```diff
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -141,6 +141,18 @@ local Input = {
         }
     },
     gesture_detector = nil,
+
+    -- internal clipboard, can be overidden to use system clipboard
+    _internal_clipboard_text = nil,
+    hasClipboardText = function()
+        return _internal_clipboard_text ~= nil and _internal_clipboard_text ~= ""
+    end,
+    getClipboardText = function()
+        return _internal_clipboard_text
+    end,
+    setClipboardText = function(text)
+        _internal_clipboard_text = text
+    end,
 }

 function Input:new(o)
```

**Comment by Frenzie** [comment]
Sure. A one-item clipboard should be quick to add.
