### ISSUE TITLE
epub only has 1 page

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#5296]
* KOReader version: 201908
* Device: both Kobo and Android

This book only shows the first page (cover) when opening in koreader:

https://www.dropbox.com/s/jag0dgyyz9uc9if/test.epub?dl=0

Calibre can read it just fine.

**Comment by Frenzie** [comment]
Btw, you can upload EPUBs on GH by renaming them to .epub.zip (or double zipping them). Dropbox isn't letting me log in atm.

> This book only shows the first page (cover) when opening in koreader:

I can't confirm. It has 224 pages. Do you have any custom styles active or something?

There's a slight chance that a crengine change fixed some issue (e.g., https://github.com/koreader/koreader/pull/5239), in which case you could try a recent nightly.

**Comment by poire-z** [comment]
No issue here either: it shows fine on the emulator and on my kobo (176 pages).
Try to clean cache/cr3cache/ and re-open.
If no change, try to Purge .sdr (make a backup, it it works, I'd like to compare the old one to the new one so we know what was the cause of that) to open it from a clean state.

**Comment by pbienst** [comment]
Style is set to auto / html5 / epub, style tweaks are off.

Couldn't find the cache directory. What is the full path? 

Purging sdr didn't help (Android doesn't even have those) .

I installed the 1 sep nightly on Android, no change. (I guess it's ok the version still reads 2018.08?)

**Comment by Frenzie** [comment]
> Couldn't find the cache directory. What is the full path?

Just `./cache`. That's `/mnt/onboard/.adds/koreader/cache` if you went with the suggested location.

**Comment by Frenzie** [comment]
> I installed the 1 sep nightly on Android, no change. (I guess it's ok the version still reads 2018.08?)

Err, read 2018.08 *where*?

**Comment by poire-z** [comment]
> Purging sdr didn't help (Android doesn't even have those) .

Android has it. It's just not available for the currently opened book (if you access it from History). Quit to File manager, and it should be enabled.

Then, I have no idea what's the problem :|

**Comment by pbienst** [comment]
Oops, I obviously meant '2019.8'. I get the number in the 'version' command in the top right hamburger menu.

Found the cache directory on Kobo (which is still running the official release), deleting it has no effect. Couldn't find the cache on Android, though. internal storage/Android/data/org.koreader.launcher/files does not contain any files, not even hidden files.

I don't have sdrs on Android since my books are on an external sdcard, in a directory controlled by SyncThing.

**Comment by poire-z** [comment]
> I don't have sdrs on Android

OK, so may be the settings (.lua) are in koreader/history/ ?
You're sure your issue is with the exact book you uploaded ? :)

**Comment by poire-z** [comment]
May be looking at the crash.log on your Kobo (easier to debug than Android) would tell you and us more ?

**Comment by Frenzie** [comment]
> Oops, I obviously meant '2019.8'. I get the number in the 'version' command in the top right hamburger menu.

Right, but more to the point does it say anything after 2019.08? Because if not then you're on the stable, not a nightly.

On Android it should be /sdcard/koreader/cache.

**Comment by pbienst** [comment]
Just to be sure I have the right book, I redownloaded it again from dropbox and saved it in a different directory. No change.

Found the history and cache under Android. Deleting them did not help.

There is nothing after '2019.08', even though I did install the 2019.8-78 apk.

Nothing funky in the Kobo logs:

https://www.dropbox.com/s/0do2i4vs13g4vah/crash-20190901.log?dl=0

**Comment by Frenzie** [comment]
@poire-z I wasn't really expecting this, but in 2019.08 it actually displays only one page!

![Screenshot_20190901_175710](https://user-images.githubusercontent.com/202757/64078994-fadce800-cce1-11e9-8e51-f3a34b498fe6.png)

@pbienst Anyway, that means it's already fixed, whatever it is. O-o

**Comment by poire-z** [comment]
Oh...
Can you check how that does with this 2019.08 and just a current libcrengine.so? To quickly check if it's really crengine related?

**Comment by Frenzie** [comment]
Is that still fully compatible? It's the AppImage (very useful to check old versions), so you can just run it with `--appimage-extract`.

**Comment by Frenzie** [comment]
@poire-z Yup, it loads all pages with the most recent libcrengine.so dropped into place.

**Comment by poire-z** [comment]
OK... looking at which commit solved this, I wanna knooow.

**Comment by Frenzie** [comment]
@poire-z The quickest way might be to go through the AppImages following crengine commits. Or maybe not. Could be faster to just checkout commits in the crengine submodule and build it. /shrugs

**Comment by poire-z** [comment]
Looks like https://github.com/koreader/crengine/pull/305/commits/51cba9e985861f7bf68afe876528ebf714e86577 did.

**Comment by Frenzie** [comment]
Weird. Is that related to one of these warnings by the EPUB validator perhaps?

```
Filename contains spaces, therefore URI escaping is necessary. Consider removing spaces from filename.
```

(There are a lot of errors and warnings.)

**Comment by poire-z** [comment]
Some `&amp;` in the content.opf:
```
TRACE codeBasePrefix is empty for path
DEBUG Checking fragment: titlepage.xhtml
TRACE http-equiv content-type:  content="text/html; charset=utf-8"/
TRACE ldomNode::applyNodeStylesheet()
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_000.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_001.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_002.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_003.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_004.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_005.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_006.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_007.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_008.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_009.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_010.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_011.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_012.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_013.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_014.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_015.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_016.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_017.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_018.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_019.html
DEBUG Checking fragment: Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_020.html
TRACE codeBasePrefix is empty for path ./
INFO ldomNode::registerDocument() - new index = 3
DEBUG setDocFlags(0000)
INFO ldomNode::unregisterDocument() - for index 3
DEBUG EPUB: 1 documents merged <======== only ONE
```
```
  <manifest>
    <item href="titlepage.xhtml" id="titlepage" media-type="application/xhtml+xml"/>
    <item href="Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_000.html" id="html21" media-type="application/xhtml+xml"/>
    <item href="Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_001.html" id="html20" media-type="application/xhtml+xml"/>
    <item href="Scheer,K.-H.&amp;Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_002.html" id="html19" media-type="application/xhtml+xml"/>
```
And in the zip, no `&amp;` :
```
     4914  2014-03-10 17:12   Scheer,K.-H.&Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_000.html
     5474  2014-03-10 17:12   Scheer,K.-H.&Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_001.html
    18854  2014-03-10 17:12   Scheer,K.-H.&Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_002.html
      799  2014-03-10 17:12   titlepage.xhtml
```
So, good that my minor fix helped there :)

**Comment by poire-z** [comment]
Once fixed:
```
2019/09/01 18:23:23.0950 DEBUG Checking fragment: Scheer,K.-H.&Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_001.html
2019/09/01 18:23:23.0959 TRACE CSS file href: stylesheet.css
2019/09/01 18:23:23.0960 DEBUG Setting StyleSheet attribute to stylesheet.css for document fragment
2019/09/01 18:23:23.0961 TRACE ldomNode::applyNodeStylesheet()
2019/09/01 18:23:23.0990 DEBUG Checking fragment: Scheer,K.-H.&Darlton,Clark-[Perry Rhodan-001]Operation Astree(1961)_split_002.html
2019/09/01 18:23:23.1010 TRACE CSS file href: stylesheet.css
2019/09/01 18:23:23.1012 DEBUG Setting StyleSheet attribute to stylesheet.css for document fragment
2019/09/01 18:23:23.1013 TRACE ldomNode::applyNodeStylesheet()
[...]
2019/09/01 18:23:23.2573 DEBUG EPUB: 22 documents merged   <==== good
```

Strange it never hit anybody before.
We're so proactive :)

**Comment by poire-z** [comment]
So, in short: fixed in current nightly.

**Comment by Frenzie** [comment]
PS To be clear, it's really the EPUB that's buggy. ;-)

**Comment by poire-z** [comment]
I think the EPUB is right in encoding `&` to `&amp;` in the `href=` attribute, to avoid it getting parsed to something else if followed by crap.

**Comment by Frenzie** [comment]
Oh, I misread. `&amp;` should be encoded in XML/HTML. If that `&amp;` wasn't resolved it was crengine's bug.

(Still, that EPUB has a ton of issues.)
