### ISSUE TITLE
Error reading EPUB format

### ISSUE THREAD

**Issue by fred777** [koreader/koreader#8222]
* KOReader version: 2021.08
* Device: Android and Linux

#### Issue
I bought a DRM-free epub which KOReader is unable to open. In KOReader's file browser it does not display the cover and instead of the book title it just says "ERROR: Error reading EPUB format". When I try to open it, it will just display the same message + "Cannot open document".

Other epub viewers like Calibre have no issues and epubcheck does not print any errors/warnings. 

In addition to the Android version on my Smartphone and my eInk reader, I tried KOReader on Linux => same error and no additional info from console output: "WARN  Cre error loading file: Error reading EPUB document"

It's EPUB version 2.0.1 according to epubcheck and I am able to browse the epub file structure via file explorer as well as Calibre so I guess there is no file corruption but some content-related error.

META-INF/encryption.xml looks a bit suspicious to me (I'm not an epub-professional, just tinkering around). It looks like this:

```
<encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container" xmlns:enc="http://www.w3.org/2001/04/xmlenc#">
<enc:EncryptedData>
<enc:EncryptionMethod Algorithm="http://www.idpf.org/2008/embedding"/>
<enc:CipherData>
<enc:CipherReference URI="OEBPS/font/MyriadPro-Bold.otf"/>
</enc:CipherData>
</enc:EncryptedData>`
....
</enc:EncryptedData>
</encryption>
```
... but I don't know if this is the right direction of investigation.

How to proceed with debugging?

#### Steps to reproduce
Unfortunately I cannot publish the epub file here due to copyright restrictions.

**Comment by Frenzie** [comment]
https://www.mobileread.com/forums/showthread.php?t=267998

**Comment by Frenzie** [comment]
> I bought a DRM-free epub which KOReader is unable to open.

PS Is there any objection to mentioning it by name? If it's from Humble Bundle for example, I might already have it.

**Comment by fred777** [comment]
Thanks for scrambler! I just tried it -> KOReader just does not have any issue with the scrambled epub :rofl: 

It's a German ebook only available from German book stores, I doubt you have it, it never was on sale on humblestore.

**Comment by Frenzie** [comment]
It's true that my German-language books are almost exclusively on paper, but you'll have to tell me where to get German DRM-free EPUBs. Not sure why you're being so mysterious anyway. ;-)

**Comment by fred777** [comment]
> It's true that my German-language books are almost exclusively on paper, but you'll have to tell me where to get German DRM-free EPUBs. Not sure why you're being so mysterious anyway. ;-)
Naming the book would expose private details I don't like to share here ;-) 
 
But can maybe figure out myself what's wrong with the book if someone could point me towards more debugging options like extended log output / traces or how to hook the Linux-version of KOReader to a GUI debugger and setting break points...

PS: we have many DRM-free book stores here, they often only apply watermarking.

**Comment by poire-z** [comment]
You can try trimming bits inside the EPUB `something.opf` file. Also look for the filename of the files referenced there (that scrambling may have rename), consecutive spaces or url-encode bad/missing have been the cause of failures in the past.

**Comment by Frenzie** [comment]
Yeah, given German something like ß (or even ë) might be a potential suspect.

**Comment by fred777** [comment]
Ok, I got a step further. It's not related to the uncompressed contents of the epub file!

When I just extract the contents and re-compress them into a new epub file with a zip archiver, KOReader does not have any issues.

So the problems lies in the compression layer.

**Comment by fred777** [comment]
zipinfo about original epub:
```
Archive:  test.epub.zip
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                   3073006 (00000000002EE3EEh)
  Actual end-cent-dir record offset:       3072984 (00000000002EE3D8h)
  Expected end-cent-dir record offset:     3072984 (00000000002EE3D8h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 126 entries.
  The central directory is 9784 (0000000000002638h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 3063200 (00000000002EBDA0h).


Central directory entry #1:
---------------------------

  mimetype

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
  version of encoding software:                   1.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   1.0
  compression method:                             none (stored)
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2014 Aug 10 09:45:56
  32-bit CRC value (hex):                         2cab616f
  compressed size:                                20 bytes
  uncompressed size:                              20 bytes
  length of filename:                             8 characters
  length of extra field:                          0 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  non-MSDOS external file attributes:             000000 hex
  MS-DOS file attributes (00 hex):                none
...
```

Repackaged version:
```
Archive:  test2.epub
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                   3079885 (00000000002EFECDh)
  Actual end-cent-dir record offset:       3079863 (00000000002EFEB7h)
  Expected end-cent-dir record offset:     3079863 (00000000002EFEB7h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 131 entries.
  The central directory is 13206 (0000000000003396h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 3066657 (00000000002ECB21h).


Central directory entry #1:
---------------------------

  META-INF/

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   3.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   1.0
  compression method:                             none (stored)
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2021 Sep 15 15:46:54
  file last modified on (UT extra field modtime): 2021 Sep 15 15:46:54 local
  file last modified on (UT extra field modtime): 2021 Sep 15 13:46:54 UTC
  32-bit CRC value (hex):                         00000000
  compressed size:                                0 bytes
  uncompressed size:                              0 bytes
  length of filename:                             9 characters
  length of extra field:                          24 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (040700 octal):            drwx------
  MS-DOS file attributes (10 hex):                dir 

  The central-directory extra field contains:
  - A subfield with ID 0x5455 (universal time) and 5 data bytes.
    The local extra field has UTC/GMT modification/access times.
  - A subfield with ID 0x7875 (Unix UID/GID (any size)) and 11 data bytes:
    01 04 e8 03 00 00 04 64 00 00 00.

  There is no file comment.
```

**Comment by poire-z** [comment]
We don't really speak "zip internals", so that won't help much. Having a real zip causing the issue might.

Dunno if these numbers are the real number of files, but there's a difference:
```diff
- central directory contains 126 entries.
+ central directory contains 131 entries.
```

But well, unzip & rezip might be just the solution for these rare cases.

**Comment by fred777** [comment]
Yes, I've seen that and I have no clue where these additional entries come from after repackaging. Unpacked contents are exactly the same.

But let's see if I can find clues in the zip library used by KOReader...

**Comment by fred777** [comment]
....well - I found another hint: renaming the original epub file to *.epub.zip makes KOReader open it without any issues!

**Comment by fred777** [comment]
I was able to narrow down the bug to embedded cool reader. The official version of cool reader (3.2.58-1 2021-06-13) has the same issue: epub file cannot be opened, but no issues when renamed to .epub.zip

**Comment by Frenzie** [comment]
The .zip is probably opened with MuPDF, but presumably not as if it were an EPUB.

(As an aside, you can long-press → open with to use MuPDF.)

**Comment by fred777** [comment]
Well - if I try to open the epub via MuPDF engine, KOReader will complain "No reader engine for this file or invalid file." And if I try to open it with standalone MuPDF it will say 
```
error: EPUB is locked by DRM
mupdf: error: cannot open document
```
...which is not true.

But standalone MuPDF works with the file renamed to .epub.zip though - which CoolReader does not.

Life is strange sometimes :)

**Comment by Frenzie** [comment]
I guess you'll have to run it `kodev run -g`, if you know how to use gdb. (It defaults to Nemiver because I like it as a frontend to gdb.)

```
$ kodev run --help

usage: run <OPTIONS> <TARGET>

OPTIONS:

    -h X, --screen-height=X  set height of the emulator screen (default: 720)
    -w X, --screen-width=X   set width of the emulator screen (default: 540)
    -d X, --screen-dpi=X     set DPI of the emulator screen (default: 160)
    -b, --no-build           run reader without rebuilding
    -n, --no-debug           no debugging symbols (requires rebuilding)
    -t, --disable-touch      use this if you want to simulate keyboard only devices
    -s FOO --simulate=FOO    simulate dimension and other specs for a given device model
                             supported model: hidpi, kobo-forma, kobo-aura-one, kobo-clara, kindle-paperwhite, kobo-h2o, legacy-paperwhite, kindle
    -g X, --gdb=X            run with debugger (default: nemiver)
    -p, --graph              graph memory use (requires gnuplot)
    -v X, --valgrind=X       run with valgrind (default: "valgrind --tool=memcheck --trace-children=yes --leak-check=full --track-origins=yes --show-reachable=yes")
    -c, --callgrind          run with valgrind's callgrind (valgrind --tool=callgrind --trace-children=yes)
    -S, --no-catchsegv       prevents wrapping by catchsegv

TARGET:

    android         install and run KOReader on an Android device connected through ADB
```

**Comment by poire-z** [comment]
> META-INF/encryption.xml looks a bit suspicious to me 

What if you remove this file ?
Was it still there in the scrambled epub (and/or referenced in the opf if it happened to be) ?

**Comment by fred777** [comment]
> > META-INF/encryption.xml looks a bit suspicious to me
> 
> What if you remove this file ?
> Was it still there in the scrambled epub (and/or referenced in the opf if it happened to be) ?
No, this was a false guess from myself. The culprit turned out to lie within the binary structure of the zip compression. The actual contents are sane and the epub will work flawlessly as soon as I extract and recompress all contents. No decryption involved at all.

**Comment by Frenzie** [comment]
Stupid question, but did you change the line numbers post-building?

**Comment by fred777** [comment]
Why should I!!?? I'm working with Visual Studio (C++ and C#) and IntelliJ (Java) professionally and have never seen issues like this with with debugging. Seems to be a gcc/gdb flavor.

I really would like to track that epub issue down and post a pull request but without a working dev environment it's not worth the effort.

**Comment by Frenzie** [comment]
> Why should I!!??

I think you misconstrued that statement. I'm just saying if you edit the files after compilation it's not going to auto-recompile and the line numbers will be off. ;-)

**Comment by Frenzie** [comment]
PS https://gitter.im/koreader/koreader

**Comment by Frenzie** [comment]
PPS You could also just use https://github.com/buggins/coolreader if that's easier for you.

**Comment by fred777** [comment]
I fixed it: https://github.com/buggins/coolreader/pull/315

**Comment by cyphar** [comment]
I believe this was fixed by #8360.

**Comment by Biont** [comment]
I just had a look at the current nightly version and while I can indeed open my 
epubs again, the file browser fails to display any cover art with the same error message.

**Comment by NiLuJe** [comment]
What if you force a metadata refresh? (it's in the long press menu).

**Comment by Biont** [comment]
That works! Thank you and sorry for disturbing then. Still getting used to things
