### ISSUE TITLE
FR: Logical Page count for crengine formats.

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#9020]
Currently page numbers are based on screen size for crengine formats.

An optional 'logical' page count would be nice, analogous to how adobe counts (1024 compressed bytes == 1 page) or kindle locations (125 characters including space / 23 words).

This kind of page counts don't change based on tweaks and good for referencing (e.g. in exported notes).

**Comment by poire-z** [comment]
(I've always felt using logical/artificial page numbers like these other readers was a needed trick to be able to have "pages" numbers without the need to render the full document to actually have "visual/real pages" numbers that is what the user really sees and naturally expects. So, the speed they get of opening/rerendering vs. crengine, they pay with bad page number quality.)
But OK, I get how some stable page numbers may be welcome with exported highlights/bookmarks.

One idea, to not clutter frontend with another page number handling/view (we have quite a few: rendered pages, rendered pages with non-linear flows hidden, source/reference page numbers...) would be to re-use the PageMap support added by #6004.
If crengine notices existing "source" page numbers in an EPUB: use that for "Reference pages", as they are stable and "real" (as they map to a real paperbook page numbers).
If no such source page numbers in the EPUB, or some other kind of doc format, and if the user as enabled doing that: have crengine in its XML parsing / DOM building / text node handler keep a counter of the amount of chars fed, and it would itself add items in this PageMap internal object, that frontend would use just as if it were from an EPUB - so we get all the benefits from what's already exists (page number in footer and ToC, page numbers in margin, etc...)

**Comment by poire-z** [comment]
Added some support in crengine for generating synthetic page numbers as part of the PageMap infrastructure.
It's not yet enabled, as it needs some thinking on how to expose (and not impose :) the feature in KOReader and its menu & widgets.

It can be forced enabled, to see how it would look/work with:
```diff
--- a/frontend/apps/reader/modules/readerpagemap.lua
+++ b/frontend/apps/reader/modules/readerpagemap.lua
@@ -45,6 +45,8 @@ function ReaderPageMap:_postInit()
     if self.ui.document.info.has_pages then
         return
     end
+    -- XXX Do this only if requested by the user
+    self.ui.document:buildSyntheticPageMapIfNoneDocumentProvided(1024)
     if not self.ui.document:hasPageMap() then
         return
     end
@@ -314,3 +321,7 @@ function ReaderPageMap:addToMainMenu(menu_items)
         -- @translators This and the other related ones refer to alternate page numbers provided in some EPUB books, that usually reference page numbers in a specific hardcopy edition of the book.
-        text = _("Reference pages"),
+        -- text = _("Reference pages"),
+        text_func = function()
+            if self.ui.document:isPageMapSynthetic() then return _("Synthetic pages") end
+            return _("Reference pages")
+        end,
         sub_item_table ={
```

I've been using 1024, 1 page every 1024 chars, which works somehow quite well with my default font size on my small emulator and my high dpi Kobo. Dunno if some other number would be preferable and backed by some studies or other tool/reader.

**Comment by Frenzie** [comment]
I think something like 1500 is typical in books, but ereaders probably tend to have fewer. Or in any case my H2O is somewhat like a paper book page with the bottom cut off.

**Comment by dmalinovsky** [comment]
> It can be forced enabled, to see how it would look/work with:

@poire-z, it's a great addition, thank you very much! Do you think it's possible to convert it to a user patch, so it will survive version updates?

**Comment by dmalinovsky** [comment]
Something like this, perhaps? https://gist.github.com/dmalinovsky/69fd68af7848008b1cc80a76961f2d77

```lua
local ReaderPageMap = require("apps/reader/modules/readerpagemap")
local postInit_orig = ReaderPageMap._postInit

ReaderPageMap._postInit = function(self)
    self.ui.document:buildSyntheticPageMapIfNoneDocumentProvided(1818)

    -- Run original code
    postInit_orig(self)
end
```

**Comment by poire-z** [comment]
^ Looks fine, and if it works, well, it works :)

**Comment by dmalinovsky** [comment]
@poire-z, can you perhaps add a "user patch available" label for this one? Or whatever the label's name is.

**Comment by ZHANYLone** [comment]
> Something like this, perhaps? https://gist.github.com/dmalinovsky/69fd68af7848008b1cc80a76961f2d77
> 
> ```lua
> local ReaderPageMap = require("apps/reader/modules/readerpagemap")
> local postInit_orig = ReaderPageMap._postInit
> 
> ReaderPageMap._postInit = function(self)
>     self.ui.document:buildSyntheticPageMapIfNoneDocumentProvided(1818)
> 
>     -- Run original code
>     postInit_orig(self)
> end
> ``` 
> 
> I tested it on my device, and this patch works.

Sorry, I'm a bit stupid. Can I ask? 
Do I need to set this file (.lua) in folder koreader/patches? Or do I need to do something more? Can you explain how to install this patch?

**Comment by jonnyl2** [comment]
>Can you explain how to install this patch?

https://github.com/koreader/koreader/wiki/User-patches

**Comment by dmalinovsky** [comment]
> how hard would it be to add this in the menu?

It'll be visible in the menu if you add this patch (or your ePub has logical page numbers already).

**Comment by poire-z** [comment]
> how hard would it be to add this in the menu?

If it was to be part of the main features, it would need a little more thinking about how to handle toggling it (ie. what to do when enabling it, when disabling it: reloading, what else to drop/reload), and if it should be per-document, or have a global setting, and if global, if you had some need to disable it for some docs, etc...
So, maybe you guys should use this patch for a while (so, somehow acting as having that globally enabled), and report how this goes for you, and how's the experience and needs.

> important: the alt statusbar won't display them. cheers

Well, the statusbar, being not ours (but handled by the engine), only display internal/screen pages numbers: it does not handle Reference Pages, hidden flows.... and it will probably never will.
We don't love the top status bar. So you all should start to hate it too - this will help :)

**Comment by poire-z** [comment]
> the good thing is that it is already quasy-toggleable because the reference pages can/must be enabled manually 

Oh, right. Forgot about how it works :)
But there are still more things needed, ie: the nb of chars per page (which is harcoded in the patch) may probably be configurable, or we may provide a few presets. And how to handle the change of this value.
You may all report what value you end up using - and/or if you're just fine with any value, like the one hardcoded, or not. And how you ended up chosing your value.
And if you are fine not having your synthetic number being used when the book has real "Reference pages".

**Comment by dmalinovsky** [comment]
> And how you ended up chosing your value.

I used a particular way to convert so called "author pages" into printed pages. This is specific to [Russian books](https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BB%D0%B8%D1%81%D1%82#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE%2C%20%D0%BE%D0%B4%D0%B8%D0%BD%20%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BB%D0%B8%D1%81%D1%82,%D0%B8%20%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D0%B5%D0%BC%D1%8B%D1%85%20%D0%B2%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%BC%20%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B5.), and the formula is 40,000 / 22 = 1,888, which I chose in the patch.



> And if you are fine not having your synthetic number being used when the book has real "Reference pages".

Yes, I believe it's a correct thing to do. Real pages should always have the priority.

**Comment by jonnyl2** [comment]
Just some info to help select a number of chars per (synthetic) page for English books:

From https://kindlepreneur.com/words-per-page/:

>How many words should be on a page in a book on Amazon? 
>According to a survey of over 900 authors, there is an average of 233 words per page in a book on Amazon for nonfiction or 280 for fiction novels. Font size and other factors impact this number.
>The standard book page for books published by traditional publishing companies ranges from 250-300 words.

Plugging these into the calculator at https://charactercounter.com/characters-to-words, we get:

233 words: 1165 - 1515 chars
250 words: 1250 - 1625 chars
300 words: 1500 - 1950 chars

**Comment by ZHANYLone** [comment]
> > Do I need to set this file (.lua) in folder koreader/patches? Or do I need to do something more? Can you explain how to install this patch?
> 
> Yes, just put it there and restart KOReader. You may want to choose your own number of symbols per page — I choose one to roughly match the Pocketbook's software. 
> 
> Then you turn on this feature in "Reference pages" menu, where you can long press on "Use reference page numbers" option to use it for all books by default.

То есть у вас уже стоит как для PocketBook? Ничего менять не надо?

So you already have set page number as for PocketBook? Don't I need to change anything?

**Comment by ZHANYLone** [comment]
> > Do I need to set this file (.lua) in folder koreader/patches? Or do I need to do something more? Can you explain how to install this patch?
> 
> Yes, just put it there and restart KOReader. You may want to choose your own number of symbols per page — I choose one to roughly match the Pocketbook's software. 
> 
> Then you turn on this feature in "Reference pages" menu, where you can long press on "Use reference page numbers" option to use it for all books by default.

Can you add in the patch this function:
How many patch pages left to the end of the book and end of the chapter. Please 🙏 
Because it only shows the current patch page, where it needs to show left pages
Simple mathematics:
312/678

So left will be
678 - 312 = **366 left**

**Comment by poire-z** [comment]
And here we go with the complications :/
Reference pages, as they can be strings (ie. roman numerals, `xviii`) can't really get involved in arithmetics (substractions for "pages left").
But Synthetic pages are pure numbers, so they could, and some users would expect that.... So more kludge, more if/elseif/else branches, more stuff that we will forget to test....

**Comment by poire-z** [comment]
> Reference pages, as they can be strings (ie. roman numerals, `xviii`) can't really get involved in arithmetics (substractions for "pages left").

So, I guess if substractions are not possible, the alternative is to count the nb of "reference page" items until the target...

There are also other stuff, like the recently added ToC setting `Show chapter length` that works only with screen page - because we forget to remember there are these other options, and because handling these cases it more complicated...
So, Reference page (and Synthetic page) are doomed to be 2nd-class citizens :/ one more reason to not go (or not go too fast) as making it part of core...

**Comment by dmalinovsky** [comment]
> So you already have set page number as for PocketBook? Don't I need to change anything?

Well, the numbers won’t match identically, Pocketbook does some calculations for the pages at the end of the chapters, it seems, but it’ll be pretty close. 

Ничего делать не надо. :)

**Comment by dmalinovsky** [comment]
> So more kludge, more if/elseif/else branches, more stuff that we will forget to test....

I think this deserves refactoring, so instead of if/else one would just call service methods to get appropriate page number representation. But since I'm fine with the way it currently works, I don't want to tackle this. :)

**Comment by poire-z** [comment]
A few tweaks done to the footer and the alt/top status bar with #11873 - which may make things a bit better for you synthetic people using synthetic page numbers :)

**Comment by dmalinovsky** [comment]
Nice, thanks a lot, @poire-z! I'll check it out later.

**Comment by skylarsoulmate** [comment]
> Something like this, perhaps? https://gist.github.com/dmalinovsky/69fd68af7848008b1cc80a76961f2d77
> 
> ```lua
> local ReaderPageMap = require("apps/reader/modules/readerpagemap")
> local postInit_orig = ReaderPageMap._postInit
> 
> ReaderPageMap._postInit = function(self)
>     self.ui.document:buildSyntheticPageMapIfNoneDocumentProvided(1818)
> 
>     -- Run original code
>     postInit_orig(self)
> end
> ``` 
> 
> I tested it on my device, and this patch works.

Can you change (add to) this userpatch so that it shows how many pages are left until the end of the book, so that is, it shows: current pages 150/498, then let it show: left pages 348/498 please 🥺 I hope you understood me. I know it's not right something about code and Roman numerals like XIV etc., but I need this to show how much pages left. PLEASE HEAR ME 🙏
Sorry for comment duplication!

**Comment by dmalinovsky** [comment]
@skylarsoulmate, it doesn't look so easy, but I honestly don't see much value in this addition. We already have current and total page numbers.

**Comment by skylarsoulmate** [comment]
> @skylarsoulmate, it doesn't look so easy, but I honestly don't see much value in this addition. We already have current and total page numbers.

Oh. Sad. I just thought it would be a perfect addition! But it's sad that you don't think so. We have two options: left pages and current. But now they are both the same. It's so sad. 
Thank you, I'm always using your userpatch It is very helpful 🩷

**Comment by dmalinovsky** [comment]
> But now they are both the same.

As I understand, https://github.com/koreader/koreader/pull/11873 should fix it.

**Comment by skylarsoulmate** [comment]
> > But now they are both the same.
> 
> As I understand, https://github.com/koreader/koreader/pull/11873 should fix it. 

Thank you. Finally good news.
I wanna ask you:
Will this fix #11873 work on (change) your userpatch too?

**Comment by dmalinovsky** [comment]
> Will this fix #11873 work on (change) your userpatch too?

I didn’t test it yet, but it should. 

Через неделю проверю.

**Comment by skylarsoulmate** [comment]
> > Will this fix #11873 work on (change) your userpatch too?
> 
> I didn’t test it yet, but it should. 
> 
> Через неделю проверю. 

А это изменение уже доступно в nightly build?

**Comment by skylarsoulmate** [comment]
> > Will this fix #11873 work on (change) your userpatch too?
> 
> I didn’t test it yet, but it should. 
> 
> Через неделю проверю. 

For some reason, it still shows the same number of pages here and there - what is left  pages and what are current pages.
I tried the latest nightly build, but nothing changes. So sad, going to cry again.
Your userpatch doesn't have improved left pages number... 💔

**Comment by readinggirlfriend** [comment]
> > Will this fix #11873 work on (change) your userpatch too?
> 
> I didn’t test it yet, but it should. 
> 
> Через неделю проверю. 

can you add these changes?
1. so that the Reading Statistics show the number of paper pages read
2. and how long is left until the end of the chapter - also paper pages, not flipping pages

Please 🥺

**Comment by dmalinovsky** [comment]
I just realized this feature is using uncompressed characters while Adobe based readers are using compressed ones. I was wondering if it's possible to use as well, since some users rely on the identical page numbers across different readers.

What do you think, @poire-z?

**Comment by Frenzie** [comment]
That sounds preposterously bad?

**Comment by dmalinovsky** [comment]
> That sounds preposterously bad?

This does sound like a lame way to count the pages, to be honest. :) It's enough to use a better compression and the page numbers will skew. But it's an unofficial standard. :)

**Comment by dmalinovsky** [comment]
Fair enough, @Frenzie. I do hope more readers will use this sensible model in the future.

**Comment by jonnyl2** [comment]
>[Frenzie] On the plus side it might be fairly simple to do? But it's also worthless… What's the point if a book of the same length might show up as 500 pages or as 5000 pages depending on factors with no relation to the actual text whatsoever.

I disagree that it'd be worthless. The value comes from having a consistent reference point for any part of the book. Calling those points (or rather, sections) "pages" probably only does a disservice to its purpose. They neither refer to printed pages nor pages on screen, and can easily be mixed up with publisher-provided 'physical page numbers' and screen pages.

I like Kindle's approach of dividing e-books into _locations_. According to [this](https://wiki.mobileread.com/wiki/Page_numbers#Implementation), each location consists of 150 bytes, which includes everything, text and tags, in the html. A regular printed book of ~300 pages will have over 1000 locations. (And one screen page may have 2 or more locations.) By calling them "locations," no one is deluded into imagining a certain physical page, but can still easily share book-sections with other Kindle users and will easily refind their position when loading the same book an a different sized device (or with different layout/font settings). 

As many KOReader users also use the software on different devices, or sometimes change the font size when their eyes are tired, I think something like this would be beneficial for our case as well. Also with respect to bookmarks/highlights (c.f., #12153).

**Comment by Frenzie** [comment]
Yes, it's mild hyperbole, but the context of the discussion is whether it's a good idea to add that to the program on top of what's already there. Percentages already exist, character-based synthetic page numbers already exist, and normalized xpointers already exist.

**Comment by jonnyl2** [comment]
>Percentages already exist, character-based synthetic page numbers already exist, and normalized xpointers already exist.

And any one of these would probably be suitable to use as uniform and consistent location indicators in the UI. My main point is that thinking of them as "pages" is not necessary and only leads to confusion, especially when they clash with physical (reference) page numbers provided by the publisher (as is currently the case using the user-patch workaround).

**Comment by dmalinovsky** [comment]
@jonnyl2, for correctness sake, user patch isn't applied when there's publisher page information presented. The number I chose is roughly equivalent to a type written page of text.

**Comment by jonnyl2** [comment]
@dmalinovsky I understand. I was just thinking ahead if this logical or reference page number is ever used for other purposes, such as marking bookmark/highlight locations or measuring reading statistics. Then you wouldn't want books with publisher-reference pages behave any differently from KOReader-internal reference page numbers. At the moment you can only use one or the other, not both.

**Comment by poire-z** [comment]
> I just realized this feature is using uncompressed characters while Adobe based readers are using compressed ones. I was wondering if it's possible to use as well

Technically, this would be very hard to achieve in crengine: the uncompressed stream decompression happens very early (so we would need to cache an index of uncompress position => index in a text node) - while the page making happens very late.
This Adobe trick was done that way because it was easier for them to do so (they don't render the whole document, to it was easy by just suming each compressed xhtml file size to get the "page" number of a later xhtml).
This trick is not easy for us - so I don't think we should add kludge to mimic a stupid (but easy for them) old idea :)

**Comment by Commodore64user** [comment]
this patch is interesting however, @poire-z do you know if it's possible to make it chapter aware? that is to say it counts a page for every `x` number of characters or every time there is a new chapter, section etc.

for some context, I use the koreader page numbers, but quite like to see the reference page number on the right border (not sure why)

**Comment by poire-z** [comment]
Probably very hard (chapter depends on the ToC (which is elsewhere when we count text nodes) or on styles (which are not set yet)).


> but quite like to see the reference page number on the right border (not sure why)

But these would not be reference pages, just "logical without much logic" pages, so you'd like to see crappy page numbers on the right ? (not sure why).

**Comment by Commodore64user** [comment]
> But these would not be reference pages, just "logical without much logic" pages, so you'd like to see crappy page numbers on the right ? (not sure why).

Stop being a downer ;) obviously i prefer them real, but when they don't exist, this makes for a nice replacement. So yeah, I would like [sometimes] "crappy" numbers on my right margin

**Comment by hius07** [comment]
Menu screenshots in
- #14405

**Comment by thatsthat** [comment]
Is it correct that the new feature stable page numbers makes this patch obsolete?

**Comment by Commodore64user** [comment]
yes, the feature gives you even more control and functionality as well. Excellent job done by @hius07 

incidentally, I always found the patch would stop working after a while, once I opened the file on a computer and it was empty. As if Koreader after a while had overwrote it and deleted those two lines, weird since that has never happened with other patches.

**Comment by thatsthat** [comment]
Kuddos to @hius07 in deed! This is a function that I wanted for a long time. The patch has worked reliably for at least a year for me, but I am not a heavy user. Nevertheless, it is very nice to have this function built into KOReader! One of my favorite apps for sure.
