### ISSUE TITLE
Koreader page turn buttons do not switch with rotation

### ISSUE THREAD

**Issue by wxletter** [koreader/koreader#9223]
* KOReader version: 2022.5.1
* Device: MOAAN MIX7, it's an e-ink reader running Android 11, with physical volume control buttons

#### Issue
I enabled page turn with volume control buttons in Koreader and it works but for one problem. When I hold MIX7 with my right hand I can turn page forward with upper button and turn page backward with lower button which is fine. When I hold MIX7 with my left hand, the page rotates automatically but the page turn buttons "reversed" - page turn forward with lower button and backward with upper button, i.e. the button functions do not switch with device and page rotation.

It seems that turn page forward/backward is fixed to the volume up/down button and do not switch with rotation. I tried with some other apps (like Kindle app) without this problem.

I found this thread (https://github.com/koreader/koreader/issues/6842) about adding "rotation_map" config in koreader/frontend/device/input.lua, but unfortunately I'm not able to access koreader/frontend folder - at least this folder is not accessible without root on MIX7

#### Steps to reproduce

1. hold MIX7 with right hand and open koreader
2. turn page with volume buttons
3. hold it with left hand, and the page turn buttons are "reversed" due to rotation

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/8921557/crash.log)

**Comment by wxletter** [comment]
This problem also exists in the newly released 2022.06 version

**Comment by pazos** [comment]
> Anyone can help on this?

We rely on motivated contributors. Hopefully somebody will do it. If not you can do it. That's how every contributor started :)

> This problem also exists in the newly released 2022.06 version

And will exist in every version until this ticket is closed and hence the problem solved ;)

**Comment by wxletter** [comment]
> We rely on motivated contributors. Hopefully somebody will do it. If not you can do it. That's how every contributor started :)
> 
> >

I intended to resolve this problem by changing some config file or so, but unfortunately I don't know much about Android and those .lua files... will dig deeper to see how/what I can do about it.

**Comment by wxletter** [comment]
I found the key code of my Android e-ink reader (by running `adb shell` and `logcat | grep "keycode”`): the upper button's key code is "24" and the lower's is "25" (when they're on the right side of the device). I tested with putting a file named "event_map.lua" in koreader/settings with the below contents:

`return {
        [25] = "RPgBack",
        [24] = "RPgFwd",
}`

So is there any way to return the above values when I'm holding the device with my right hand, and return `[25] = "RPgFwd"` and `[24] = "RPgBack"` when I'm holding it with my left hand (buttons on the left)? i.e. how to define if/else statements with rotation?

**Comment by poire-z** [comment]
Looks like there is already some code that should deal with that (and your keys):
https://github.com/koreader/koreader/blob/6e647a6f4d739cd55dbcf71dff63ad554499f72c/frontend/device/input.lua#L175-L181
https://github.com/koreader/koreader/blob/6e647a6f4d739cd55dbcf71dff63ad554499f72c/frontend/device/input.lua#L491-L494

**Comment by wxletter** [comment]
> Looks like there is already some code that should deal with that (and your keys):
> 
> https://github.com/koreader/koreader/blob/6e647a6f4d739cd55dbcf71dff63ad554499f72c/frontend/device/input.lua#L175-L181
> 
> 
> https://github.com/koreader/koreader/blob/6e647a6f4d739cd55dbcf71dff63ad554499f72c/frontend/device/input.lua#L491-L494

Thanks @poire-z, but I'm not able to access koreader/frontend folder without root on my device, so I'm trying to find a way to deal with this problem without hacking it. Is there a way to make rotation_map and the codes work without accessing/editing files in koreader/frontend?

**Comment by wxletter** [comment]
> 

I understand, by "hacking" I mean to get root privilege of the Android device, since I'm not able to access koreader/frontend folder without root privilege, neither with Android file explorer nor with adb. It seems that if I can get my hands on koreader/frontend folder and the files it SHOULD work.

**Comment by wxletter** [comment]
Are you sure there's a folder named "frontend" under "sdcard/koreader" in Android? I can't see folder "frontend" and I tried to create a folder named "frontend" in folder "koreader" and succeeded.

**Comment by Frenzie** [comment]
/sdcard/koreader is just the settings. The program itself usually lives in /data/app/etc.

**Comment by wxletter** [comment]
> 

Oh... so "koreader/frontend" is not the "koreader" folder I can see under "sdcard" but rather in /data/app/etc. then it's another story of Android, sadly to say that it's probably not what I can resolve regarding this device's os.

**Comment by Frenzie** [comment]
More or less. In principle it's not excessively hard to take the APK file on your PC, change a few files and then sign it, though it's quite awkward.

**Comment by wxletter** [comment]
> More or less. In principle it's not excessively hard to take the APK file on your PC, change a few files and then sign it, though it's quite awkward.

Many thanks Frenzie, maybe awkward as it seems but it's probably the easiest way for me to resolve this problem, will try.

**Comment by CrazyCoder** [comment]
I noticed this issue on the Onyx Leaf 2 Android device which has hardware page turn buttons.

What happens is that the framework does the rotation for the buttons automatically, which works for all the system and third-party apps.

KOReader is too smart, detests that the screen is rotated and does it again, reversing what the framework did.

I replaced the code with `[framebuffer.ORIENTATION_PORTRAIT_ROTATED]  = {}` to disable KOReader rotation and it now works as expected.

What we need is a setting that will disable automatic rotation for hardware buttons in KOReader (easy) or a special Quirk for devices that do the rotation automatically (harder, needs verifying on real hardware).

I also tested with the [patched framework](https://www.mobileread.com/forums/showthread.php?p=4271047#post4271047) which disables framework processing of the hardware buttons, and KOReader works just fine without any modifications to `input.lua` (but you lose automatic button rotation in all the other apps).

**Comment by NiLuJe** [comment]
> What we need is a setting that will disable automatic rotation for hardware buttons in KOReader (easy) or a special Quirk for devices that do the rotation automatically (harder, needs verifying on real hardware).

https://github.com/koreader/koreader/pull/9691 ;).

**Comment by wxletter** [comment]
> I replaced the code with `[framebuffer.ORIENTATION_PORTRAIT_ROTATED] = {}` to disable KOReader rotation and it now works as expected.

That's great to know @CrazyCoder, however since I'm not able to "root" my device I cannot touch input.lua, do you know if there's any other way to change this setting?

**Comment by CrazyCoder** [comment]
@wxletter If you don't have root, you can build your own copy of KOReader from sources with this modification, sign it with your own keys, uninstall the official KOReader and install your modded version instead. I did exactly that. The build guide is a bit outdated in some places, and you will likely face several issues not covered in the guide, but it's doable with some googling.

**Comment by CrazyCoder** [comment]
@NiLuJe Yes, we need something like that for Android devices in general. Maybe add a developer/advanced option to disable it so that we don't have to patch KOReader until the proper fix is available?

**Comment by poire-z** [comment]
Also see https://github.com/koreader/koreader/wiki/User-patches (which should work on Android) for this kind of quick hacking or replacing some existing property.

**Comment by NiLuJe** [comment]
^ This. (You can `nil` it at any time after `Device` has been initialized).

**Comment by CrazyCoder** [comment]
I've made a patch and it works! Thanks for the tips. Place the file inside `koreader\patches` on the device storage.

[2-disable-hw-button-rotation.lua](https://gist.githubusercontent.com/CrazyCoder/fdf7108afc592c0f41afc75a8303c86f/raw/fc49fc2d1f818808c778754750cd918286fc3649/2-disable-hw-button-rotation.lua)

**Comment by wxletter** [comment]
> I've made a patch and it works! Thanks for the tips. Place the file inside `koreader/patches` on the device storage.
> 
> [2-disable-hw-button-rotation.lua](https://gist.githubusercontent.com/CrazyCoder/fdf7108afc592c0f41afc75a8303c86f/raw/fc49fc2d1f818808c778754750cd918286fc3649/2-disable-hw-button-rotation.lua)

I placed [2-disable-hw-button-rotation.lua](https://gist.githubusercontent.com/CrazyCoder/fdf7108afc592c0f41afc75a8303c86f/raw/fc49fc2d1f818808c778754750cd918286fc3649/2-disable-hw-button-rotation.lua) under sdcard/koreader/patches and it's still the same, do I need to add/edit other files that'll be referenced by this .lua file?

**Comment by NiLuJe** [comment]
> * KOReader version: 2022.5.1

You need to update to a current release ;).

**Comment by wxletter** [comment]
> > * KOReader version: 2022.5.1
> 
> You need to update to a current release ;).

I forgot to mention that I uninstalled 2022.5.1, installed 2022.10 and then placed [2-disable-hw-button-rotation.lua](https://gist.githubusercontent.com/CrazyCoder/fdf7108afc592c0f41afc75a8303c86f/raw/fc49fc2d1f818808c778754750cd918286fc3649/2-disable-hw-button-rotation.lua) under sdcard/koreader/patches, and the keys still work as before, couldn't figure it out.

**Comment by pazos** [comment]
You will need to figure out what happens with adb.

First check that the patch is applied without errors.

If that's the case then double check the key events your device produces. See https://github.com/koreader/koreader/issues/5761#issuecomment-573345775

**Comment by innocenat** [comment]
I poked around the code and found  that the patch actually didn't work, at least in the latest version.

Because the patch just does `Device.input.rotation_map = nil`, in the latest version, it get re-set by the Input script because it now has nil check.

https://github.com/koreader/koreader/blob/master/frontend/device/input.lua#L264-L271

Instead, I just remapped it to be entirely blank and it works beautifully on my Boox Leaf 2.

```lua
local logger = require("logger")
local Device = require("device")
Device.input.rotation_map = {
    [0] = {},
    [1] = {},
    [2] = {},
    [3] = {},
}
logger.info("Hardware button rotation disabled by user patch")
```

**Comment by NiLuJe** [comment]
I did mention that the patch would have to run *after* Device's init (it's the only codepath instantiating Input, and both are singletons).

**Comment by innocenat** [comment]
With all respect to you as a project member on this wonderful software, there are no simple documentation as to which patch number run before or after Device init, and whether there even is one for after Device init.

My intention of posting the alternative patch is to help other people with the same problem who may stumbled upon this issue :)

**Comment by innocenat** [comment]
That page mention nothing of where Device is initialised. I would guess you know since, well, you are a project member, but we (the one who isn't familiar with koreader but want to use them properly) don't.

Also am I missing something or when someone ask that the aforementioned patch (with nil) doesn't work, you suggested them to update to the current version, which is 2022.10, which you also know doesn't fixed said problem?

**Comment by NiLuJe** [comment]
> That page mention nothing of where Device is initialised. I would guess you know since, well, you are a project member, but we (the one who isn't familiar with koreader but want to use them properly) don't.

True enough, although process of elimination and common sense would get you there anyway since !early was kind of the point ;).

> Also am I missing something or when someone ask that the aforementioned patch (with nil) doesn't work, you suggested them to update to the current version, which is 2022.10, which you also know doesn't fix said problem?

Yup, I possibly thought it made it in 2022.10 in my original answer, which is why I clarified here.

**Comment by wxletter** [comment]
> Instead, I just remapped it to be entirely blank and it works beautifully on my Boox Leaf 2.
> 
> ```lua
> local logger = require("logger")
> local Device = require("device")
> Device.input.rotation_map = {
>     [0] = {},
>     [1] = {},
>     [2] = {},
>     [3] = {},
> }
> logger.info("Hardware button rotation disabled by user patch")
> ```

Thanks so much @innocenat , this saved my world.
And then I run into another issue.
In the system settings I configured the upper button (no matter how I hold the device) for next page and lower button for previous page, this setting works find for other apps but is reversed for KOreader: when I press the up button KOreader turns to previous page and lower button to next page. The rotation map works fine, just the 2 button functions are reversed in KOreader. Could this be fixed easily? If no then I'll live with it, no big deal :)

**Comment by NiLuJe** [comment]
@wxletter: c.f., the keymapping section of https://github.com/koreader/koreader/wiki/Android-tips-and-tricks

**Comment by wxletter** [comment]
> 

I read this thread but couldn't figure out how/what to do due to my poor knowledge of .lua and how KOerader works...
This reversed button issue has gone away after I restarted KOreader several times, don't know why but now it works perfectly fine with the config provided by @innocenat

**Comment by wxletter** [comment]
Hope this can be fixed with future releases, or I'm not sure for how long the patch file will survive :)

**Comment by pazos** [comment]
> Hope this can be fixed with future releases, or I'm not sure for how long the patch file will survive :)

There's nothing to fix. Please use the patch and comment here if some day it stops working.

**Comment by Denisuu** [comment]
I'm a bit confused on how I can get this to work. I also have the Onyx Leaf 2 with KOreader version v2022.11

Placing [2-disable-hw-button-rotation.lua](https://gist.githubusercontent.com/CrazyCoder/fdf7108afc592c0f41afc75a8303c86f/raw/fc49fc2d1f818808c778754750cd918286fc3649/2-disable-hw-button-rotation.lua) under `koreader/patches/` doesn't work.

Do I need to make a folder `koreader/frontend/device/`, then put [input.lua](https://github.com/koreader/koreader/blob/1c42641733b59b4fdea0df8a5c4f102790dbeb52/frontend/device/input.lua#L264-L271) in there and modify lines `264 - 271`?  Do I need both the patch and the modified input.lua? Do I need to use KoReader 2022.10 or below?

**Comment by NiLuJe** [comment]
The patch should behave, although only on 2022.11; the latest nightlies would require a different patch (c.f., my latest merge).

**Comment by Denisuu** [comment]
The patch doesn't work, it should be as simple as making a folder and just putting the file in right? I'm not using a nightly build.  Am I missing something. Do you need to enable it in settings or something.

There doesn't seem to be an imput.lua file on my device either.

**Comment by Denisuu** [comment]
I re-installed the latest APK from Github, it's working now! 
Thanks everyone, happy holidays!

**Comment by NiLuJe** [comment]
And now that I'm back home, for nightlies post-#9935 or releases >= 2022.12, this patch becomes

```
local logger = require("logger")
local Device = require("device")
Device.input:disableRotationMap() = nil
logger.info("Hardware button rotation disabled by user patch")
```

**Comment by Denisuu** [comment]
I don't think I understood post-#9935 fully. You do need root access and modify the files below right? 

```
Leaf2:/ # find /data -name "input.lua"                                                                                                                                                       
/data/data/org.koreader.launcher/files/frontend/device/input.lua
```

Not just make a folder `/sdcard/koreader/frontend/device/`  and put `input.lua` in there. 

The current patch doesn't work with v2022.11 from F-Droid only with the one from GitHub.

Thanks for checking!

**Comment by NiLuJe** [comment]
User-patches are disabled in the F-Droid flavor (per F-Droid restrictions about "no runtime code modification") ;).

No the post above was just a heads-up for patch users that this would need a different patch starting with the next release (or current nightlies).

You don't have access to the actual app code on Android (barring root access), hence the patches ;).

**Comment by shin3c** [comment]
> And now that I'm back home, for nightlies post-#9935 or releases >= 2022.12, this patch becomes
> 
> ```lua
> local logger = require("logger")
> local Device = require("device")
> Device.input:disableRotationMap()
> logger.info("Hardware button rotation disabled by user patch")
> ```
> 
> Barring any future API changes, the variant posted in [#9223 (comment)](https://github.com/koreader/koreader/issues/9223#issuecomment-1324519632) will still work, too (because it's essentially what the new method does ;p)!

This patch is still valid for Onyx Boox Leaf on version 2023.03.

**Comment by kesselborn** [comment]
for the Pocketbook Era I had to use the following patch (the others did not work correctly):

```
local logger = require("logger")
local Device = require("device")
Device.input.rotation_map = {
   [0] = { Up = "Up",  Right = "Right", Down = "Down",    Left = "Left", LPgFwd  = "LPgFwd", LPgBack = "LPgBack",  RPgFwd  = "RPgFwd", RPgBack = "RPgBack" },
   [1] = { Up = "Right", Right = "Down", Down = "Left",  Left = "Up",    LPgBack = "LPgFwd",  LPgFwd  = "LPgBack", RPgBack = "RPgFwd",  RPgFwd  = "RPgBack" },
   [2] = { Up = "Down",  Right = "Left", Down = "Up",    Left = "Right", LPgFwd  = "LPgBack", LPgBack = "LPgFwd",  RPgFwd  = "RPgBack", RPgBack = "RPgFwd" },
   [3] = { Up = "Left",  Right = "Up",   Down = "Right", Left = "Down" }
}
logger.info("Hardware button rotation disabled by user patch")

```

it could probably be simplified with empty `{}` for some positions, but it works and I am too lazy to mount/unmount for trying it out

**Comment by foxmean** [comment]
Is this possible to included in the future released? Because I installed KOreader from F-Droid, I cannot install this patch. My device is Boox Leaf 2 on firmware 2023-11-29_16-54_3.5_c3a890b73.

**Comment by foxmean** [comment]
Never mind. I've just download KOReader 2024.01 "Snowy Summit" directly and install plugin from @NiLuJe 

> And now that I'm back home, for nightlies post-#9935 or releases >= 2022.12, this patch becomes
> 
> ```lua
> local logger = require("logger")
> local Device = require("device")
> Device.input:disableRotationMap()
> logger.info("Hardware button rotation disabled by user patch")
> ```
> 
> Barring any future API changes, the variant posted in [#9223 (comment)](https://github.com/koreader/koreader/issues/9223#issuecomment-1324519632) will still work, too (because it's essentially what the new method does ;p)!

And it valid for Boox Leaf 2 on firmware 2023-11-29_16-54_3.5_c3a890b73.

**Comment by Denisuu** [comment]
> And now that I'm back home, for nightlies post-#9935 or releases >= 2022.12, this patch becomes
> 
> ```lua
> local logger = require("logger")
> local Device = require("device")
> Device.input:disableRotationMap()
> logger.info("Hardware button rotation disabled by user patch")
> ```
> 
> Barring any future API changes, the variant posted in [#9223 (comment)](https://github.com/koreader/koreader/issues/9223#issuecomment-1324519632) will still work, too (because it's essentially what the new method does ;p)!

This patch doesn't seem to work anymore on KOReader 2024.07, as soon as I press the buttons I get:

`V/ActivityThread (2540): reportTopResumedActivityChanged -> onActivityTopResumed`

As soon as I remove the patch buttons work again, but obviously not correctly when I rotate te device.

**Comment by NiLuJe** [comment]
An actually actionable crash log would be useful.

**Comment by Denisuu** [comment]
> An actually actionable crash log would be useful.

I had to trigger it a couple of times before I got a log, this is the [crash.log](https://github.com/user-attachments/files/16379985/crash.log)

I guess the important lines are these:

```
07-25 17:13:57.213 V/dlopen  ( 2818): sys_dlopen - loading library /data/user/0/org.koreader.launcher/files/common/ssl.so (in local namespace)
07-25 17:13:57.214 W/linker  ( 2818): Warning: "/data/user/0/org.koreader.launcher/files/common/ssl.so" unused DT entry: DT_RPATH (type 0xf arg 0x129b) (ignoring)
07-25 17:13:57.354 I/KOReader( 2818): Loading plugins from directory: /storage/emulated/0/koreader/plugins/
07-25 17:13:58.613 E/NativeThread( 2818): Failed to run script: frontend/device/input.lua:704: attempt to index field 'rotation_map' (a nil value)
```

**Comment by NiLuJe** [comment]
That.. doesn't make much sense, unless you have a really broken variant of the patch that just does `Device.input.rotation_map = nil` :?

Does this work any better?

```
local logger = require("logger")
local Device = require("device")
Device.input.rotation_map[0] = {}
Device.input.rotation_map[1] = {}
Device.input.rotation_map[2] = {}
Device.input.rotation_map[3] = {}
logger.info("Hardware button rotation disabled by user patch (wip)")
```

**Comment by Denisuu** [comment]
> That.. doesn't make much sense, unless you have a really broken variant of the patch that just does `Device.input.rotation_map = nil` :? Or a borked c/p where you call `Device.input.disableRotationMap()` instead of ` Device.input:disableRotationMap()`?
> 
> Does this work any better?
> 
> ```
> local logger = require("logger")
> local Device = require("device")
> Device.input.rotation_map[0] = {}
> Device.input.rotation_map[1] = {}
> Device.input.rotation_map[2] = {}
> Device.input.rotation_map[3] = {}
> logger.info("Hardware button rotation disabled by user patch (wip)")
> ```

No, I'm still seeing the same error and I don't understand it either. Is there a way to get a more detailed log? Usually, it only shows a few lines like this, and occasionally the error appears. Are there any dependency system apps for it to work? 

`V/ActivityThread (): reportTopResumedActivityChanged -> onActivityTopResumed`

**Comment by NiLuJe** [comment]
Android is terrible,.

If you have verbose debug enabled, `pidcat` (which I've never use dmyself) or `adb logcat 'KOReader:V ApkUpdater:V Assets:V Device:V dlopen:V EPD:V EventReceiver:V Lights:V Surface:V LuaJIT:V MainActivity:V NativeGlue:V NativeThread:V Timeout:V ActivityManager:V AndroidRuntime:V DEBUG:* *:F'` should catch everything relevant.

**Comment by Denisuu** [comment]
I'm not sure what it's for, or if  it's causing the crash, but the [pidcat.log](https://github.com/user-attachments/files/16390703/pidcat.log) mentions that libbeluga.so is not found on lines 1 and 654:

`b'\x1b[31m                 Zygote\x1b[0m \x1b[30;103m W \x1b[0m Unable to open libbeluga.so: dlopen failed: library "libbeluga.so" not found.'
`
Here are the [adb logcat.log](https://github.com/user-attachments/files/16390720/adb.logcat.log) and full [crash.log](https://github.com/user-attachments/files/16390729/crash.log)

**Comment by Denisuu** [comment]
I just uninstalled KOReader, removed the folder  in the root of my internal storage and installed [KOReader 2024.04 "Sourdough"](https://github.com/koreader/koreader/releases/tag/v2024.04), then tried [KOReader 2024.01 "Snowy Summit"](https://github.com/koreader/koreader/releases/tag/v2024.01) same problem for both, so I'm starting to think it's Onyx last update that is causing the issue. I'll try a full factory reset to see if that solves the problem.

This update:
```
Model:  Leaf2 (English)
Finger: Onyx/Leaf2/Leaf2:11/2024-07-01_22-46_3.5.3_7f5c78ff3/8813:user/release-keys
Link:   http://firmware-us.boox.com/50570c969b16c994e2a4f3fc1f667837/update.upx
Size:   429,564,732
MD5:    50570c969b16c994e2a4f3fc1f667837
```

**Comment by NiLuJe** [comment]
> libbeluga.so

Probably a weird ROM-specific thingy.

----

Oh, Onyx. Joy.

**Comment by Denisuu** [comment]
> > libbeluga.so
> 
> Probably a weird ROM-specific thingy. Not anything of ours in any case.
> 
> Oh, Onyx. Joy. >_<".

Yea Onyx... I wish they'd release their kernel sources so we can port a lightweight, bloatware free AOSP rom.

I just did a full factory reset, installed [KOReader 2024.07 "Outside"](https://github.com/koreader/koreader/releases/tag/v2024.07) and the problem persists. Is there any workaround, or other place to ask for help?

**Comment by NiLuJe** [comment]
I would triple-check the actual content of the patch you're applying, because I really can't think of something else (e.g., a function call instead of a method call).

I just double-checked on a Kobo, and everything looks sound on my end.

**Comment by Denisuu** [comment]
As soon as the patch is applied even swiping to go back causes a crash. Very weird, I really hope to get this working again.

**Comment by NiLuJe** [comment]
Err, what's the stack trace for a swipe crash?

**Comment by Denisuu** [comment]
> Err, what's the stack trace for a swipe crash?

I've generated logs using all three methods again. While the cause of the crash seems to differ, I'm still not entirely sure what's happening.

The onscreen crash message still displays:
`V/ActivityThread (): reportTopResumedActivityChanged -> onActivityTopResumed`

[crash swipe.log](https://github.com/user-attachments/files/16569776/crash.swipe.log)
[logcat swipe.log](https://github.com/user-attachments/files/16569777/logcat.swipe.log)
[pidcat swipe.log](https://github.com/user-attachments/files/16569778/pidcat.swipe.log)

**Comment by Denisuu** [comment]
> Does this work any better?
> 
> ```
> local logger = require("logger")
> local Device = require("device")
> Device.input.rotation_map[0] = {}
> Device.input.rotation_map[1] = {}
> Device.input.rotation_map[2] = {}
> Device.input.rotation_map[3] = {}
> logger.info("Hardware button rotation disabled by user patch (wip)")
> ```

That didn't work but [this](https://www.mobileread.com/forums/showpost.php?p=4448508&postcount=7) fix by Renate fixed it. No more crashes and the buttons work correctly now on my Onyx Leaf 2

```
local logger = require("logger")
local Device = require("device")
Device.input.rotation_map = {[0]={}, [1]={}, [2]={}, [3]={}}
logger.info("Hardware button rotation disabled by user patch")
```

**Comment by NiLuJe** [comment]
Huh. That would imply `rotation_map` *really* is `nil` for... some reason.

(That shouldn't be even remotely possible after `Device:init`...).

And that also doesn't explain why the `disableRotationMap` patch doesn't work, because it is essentially doing the *exact* same thing as that variant, lol.

**Comment by Frenzie** [comment]
Essentially yes, but you'd have to initialize it to {} to be entirely equivalent.

**Comment by rmateu** [comment]
> That didn't work but [this](https://www.mobileread.com/forums/showpost.php?p=4448508&postcount=7) fix by Renate fixed it. No more crashes and the buttons work correctly now on my Onyx Leaf 2
> 
> ```
> local logger = require("logger")
> local Device = require("device")
> Device.input.rotation_map = {[0]={}, [1]={}, [2]={}, [3]={}}
> logger.info("Hardware button rotation disabled by user patch")
> ```

Thank you! this worked perfectly form me on Boox Leaf 2. Leaving my AI Augmented (sorry) code for anyone else that might find it useful.

```lua
-- KOReader User Patch: Disable Hardware Button Rotation
-- Device: Onyx Boox Leaf 2
--
-- INSTALLATION:
--   Place this file in your KOReader patches directory:
--   /sdcard/koreader/patches/
--   (or wherever your KOReader user data folder is located)
--
--   The filename must start with a number to control load order.
--   Rename to e.g.: 2-disable_hw_rotation.lua
--
-- EFFECT:
--   Clears the rotation_map for all four orientations (0°, 90°, 180°, 270°),
--   preventing KOReader from remapping hardware button events when the
--   device is rotated. Button events will behave identically in all
--   screen orientations.
--
-- TO UNINSTALL:
--   Simply remove this file from the patches directory and restart KOReader.

local logger = require("logger")
local Device = require("device")

-- Clear the rotation map for all four orientations.
-- Keys 0-3 correspond to: portrait, landscape (90°), reverse portrait (180°),
-- reverse landscape (270°).
Device.input.rotation_map = {[0]={}, [1]={}, [2]={}, [3]={}}

logger.info("Hardware button rotation disabled by user patch")

```
